version: "3"

services:
  app1:
    image: nginxdemos/nginx-hello
    networks:
      bw-services:
        aliases:
          - app1
    labels:
      - bunkerweb.SERVER_NAME=app1.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://app1:8080

  app2:
    image: nginxdemos/nginx-hello
    networks:
      bw-services:
        aliases:
          - app2
    labels:
      - bunkerweb.SERVER_NAME=app2.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://app2:8080

networks:
  bw-services:
    external: true
    name: bw-services
