FROM alpine:3.18@sha256:34871e7290500828b39e22294660bee86d966bc0017544e848dd9a255cdf59e0

WORKDIR /opt/init

COPY entrypoint.sh .

RUN apk add --no-cache bash && \
  chmod +x entrypoint.sh

ENTRYPOINT [ "./entrypoint.sh" ]
