"""Upgrade to version 1.7.0~beta

Revision ID: c1af042488a9
Revises: 447a2b82a6c7
Create Date: 2026-09-01 14:33:53.060269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import model

# revision identifiers, used by Alembic.
revision: str = "c1af042488a9"
down_revision: Union[str, None] = "447a2b82a6c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update the version in bw_metadata
    op.execute("UPDATE bw_metadata SET version = '1.7.0~beta' WHERE id = 1")
    # Force a Pro plugins re-check after the version change
    op.execute("UPDATE bw_metadata SET last_pro_check = NULL WHERE id = 1")
    op.create_table(
        "bw_bans",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("ip", sa.String(length=39), nullable=False),
        sa.Column("ban_scope", sa.String(length=8), nullable=False),
        sa.Column("service_id", sa.String(length=256), nullable=False),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("reason_data", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip", "ban_scope", "service_id", name="uq_bw_bans_ip_scope_service"),
    )
    with op.batch_alter_table("bw_bans", schema=None) as batch_op:
        batch_op.create_index("ix_bw_bans_active", ["revoked_at", "expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_bans_ip"), ["ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_bans_revoked_at"), ["revoked_at"], unique=False)

    op.create_table(
        "bw_metrics_baseline",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("instance_hostname", sa.String(length=256), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_name", sa.String(length=256), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("request_time", sa.Float(), nullable=True),
        sa.Column("request_length", sa.BigInteger(), nullable=True),
        sa.Column("body_bytes_sent", sa.BigInteger(), nullable=True),
        sa.Column("upstream_time", sa.Float(), nullable=True),
        sa.Column("connection_requests", sa.BigInteger(), nullable=True),
        sa.Column("http_version", sa.String(length=16), nullable=True),
        sa.Column("scheme", sa.String(length=8), nullable=True),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.Column("content_length", sa.BigInteger(), nullable=True),
        sa.Column("ssl_protocol", sa.String(length=16), nullable=True),
        sa.Column("ssl_cipher", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=16), nullable=False),
        sa.Column("asn_number", sa.Integer(), nullable=True),
        sa.Column("ip_version", sa.Integer(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_hostname", "request_id", name="uq_bw_metrics_baseline_instance_request"),
    )
    with op.batch_alter_table("bw_metrics_baseline", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_metrics_baseline_date"), ["date"], unique=False)
        batch_op.create_index("ix_bw_metrics_baseline_date_server", ["date", "server_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_baseline_instance_hostname"), ["instance_hostname"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_baseline_request_id"), ["request_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_baseline_server_name"), ["server_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_baseline_status"), ["status"], unique=False)

    op.create_table(
        "bw_metrics_requests",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("instance_hostname", sa.String(length=256), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("protocol", sa.String(length=8), server_default="http", nullable=False),
        sa.Column("ip", sa.String(length=39), nullable=False),
        sa.Column("country", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("server_name", sa.String(length=256), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("security_mode", sa.String(length=16), nullable=False),
        sa.Column("asn_number", sa.Integer(), nullable=True),
        sa.Column("asn_org", sa.String(length=256), nullable=True),
        sa.Column("listen_port", sa.Integer(), nullable=True),
        sa.Column("client_port", sa.Integer(), nullable=True),
        sa.Column("bytes_sent", sa.BigInteger(), nullable=True),
        sa.Column("bytes_received", sa.BigInteger(), nullable=True),
        sa.Column("session_time", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_hostname", "request_id", name="uq_bw_metrics_requests_instance_request"),
    )
    with op.batch_alter_table("bw_metrics_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_date"), ["date"], unique=False)
        batch_op.create_index("ix_bw_metrics_requests_date_server", ["date", "server_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_instance_hostname"), ["instance_hostname"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_ip"), ["ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_protocol"), ["protocol"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_reason"), ["reason"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_request_id"), ["request_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_security_mode"), ["security_mode"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_server_name"), ["server_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_metrics_requests_status"), ["status"], unique=False)

    op.create_table(
        "bw_resources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=True),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "name"),
    )
    op.create_table(
        "bw_certificates",
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("certificate_pem", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.Column("private_key_ciphertext", sa.LargeBinary(length=4294967295), nullable=False),
        sa.Column("private_key_nonce", sa.LargeBinary(length=12), nullable=False),
        sa.Column("private_key_key_id", sa.String(length=128), nullable=False),
        sa.Column("common_name", sa.String(length=256), nullable=False),
        sa.Column("sans", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("serial_number", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("key_type", sa.String(length=64), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("renewal_metadata", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.Column("last_renewal", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_renewal", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=True),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["resource_id"], ["bw_resources.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("resource_id"),
        sa.UniqueConstraint("fingerprint"),
    )
    with op.batch_alter_table("bw_certificates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_certificates_common_name"), ["common_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_certificates_valid_to"), ["valid_to"], unique=False)

    op.create_table(
        "bw_redirects",
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("from_path", sa.String(length=256), nullable=False),
        sa.Column("to_url", sa.String(length=512), nullable=False),
        sa.Column("status_code", sa.String(length=3), nullable=False),
        sa.Column("append_request_uri", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["bw_resources.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_table(
        "bw_resource_attachments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.String(length=256), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("match_path", sa.String(length=256), server_default="", nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["bw_resources.id"], onupdate="cascade", ondelete="cascade"),
        sa.ForeignKeyConstraint(["service_id"], ["bw_services.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_id", "service_id", "match_path"),
    )
    with op.batch_alter_table("bw_resource_attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_resource_attachments_resource_id"), ["resource_id"], unique=False)
        batch_op.create_index("ix_bw_resource_attachments_service_primary", ["service_id", "is_primary"], unique=False)

    op.create_table(
        "bw_resource_groups",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=True),
        sa.Column("method", sa.Enum("api", "ui", "scheduler", "autoconf", "manual", "wizard", name="methods_enum"), nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=True),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plugin_id"], ["bw_plugins.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("bw_resource_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_resource_groups_plugin_id"), ["plugin_id"], unique=False)

    op.rename_table("bw_ui_user_columns_preferences", "bw_ui_user_preferences")
    op.alter_column("bw_ui_user_preferences", "table_name", existing_type=sa.String(length=256), new_column_name="key", existing_nullable=False)
    op.alter_column("bw_ui_user_preferences", "columns", existing_type=model.JSONText(), new_column_name="value", existing_nullable=False)
    op.create_table(
        "bw_ui_user_webauthn_credentials",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("user_name", sa.String(length=256), nullable=False),
        sa.Column("credential_id", sa.String(length=512), nullable=False),
        sa.Column("user_handle", sa.String(length=128), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.String(length=128), nullable=True),
        sa.Column("device_type", sa.String(length=32), nullable=True),
        sa.Column("backed_up", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_name"], ["bw_ui_users.username"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bw_ui_user_webauthn_credentials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_ui_user_webauthn_credentials_credential_id"), ["credential_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_bw_ui_user_webauthn_credentials_user_name"), ["user_name"], unique=False)

    op.create_table(
        "bw_upstreams",
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("protocol", sa.String(length=16), server_default="http", nullable=False),
        sa.Column("backend_ssl", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("keepalive", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["resource_id"], ["bw_resources.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_table(
        "bw_workflows",
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("definition", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["bw_resources.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_table(
        "bw_resource_group_entries",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("group_id", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.Enum("ip", "country", "asn", "rdns", "user_agent", "uri", name="resource_kinds_enum"), nullable=False),
        sa.Column("value", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=False),
        sa.Column("comment", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["bw_resource_groups.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "order"),
    )
    with op.batch_alter_table("bw_resource_group_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_resource_group_entries_group_id"), ["group_id"], unique=False)

    op.create_table(
        "bw_resource_group_usages",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("group_id", sa.String(length=256), nullable=False),
        sa.Column("plugin_id", sa.String(length=64), nullable=False),
        sa.Column("consumer_type", sa.String(length=32), nullable=False),
        sa.Column("consumer_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["bw_resource_groups.id"], onupdate="cascade", ondelete="cascade"),
        sa.ForeignKeyConstraint(["plugin_id"], ["bw_plugins.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "plugin_id", "consumer_type", "consumer_id"),
    )
    with op.batch_alter_table("bw_resource_group_usages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_resource_group_usages_consumer_id"), ["consumer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_resource_group_usages_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bw_resource_group_usages_plugin_id"), ["plugin_id"], unique=False)

    op.create_table(
        "bw_upstream_servers",
        sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("max_fails", sa.Integer(), nullable=False),
        sa.Column("fail_timeout", sa.String(length=16), nullable=False),
        sa.Column("backup", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("down", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["bw_upstreams.resource_id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_id", "order"),
    )
    with op.batch_alter_table("bw_upstream_servers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bw_upstream_servers_resource_id"), ["resource_id"], unique=False)

    with op.batch_alter_table("bw_api_user_permissions", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_type",
            existing_type=sa.VARCHAR(length=13),
            type_=sa.Enum(
                "instances",
                "global_config",
                "services",
                "configs",
                "plugins",
                "cache",
                "web_cache",
                "bans",
                "jobs",
                "resource_groups",
                "certificates",
                "redirects",
                "upstreams",
                "workflows",
                name="api_resource_enum",
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("bw_custom_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=21),
            type_=sa.Enum(
                "http",
                "stream",
                "server_http",
                "server_stream",
                "default_server_http",
                "modsec",
                "modsec_crs",
                "crs_plugins_before",
                "crs_plugins_after",
                name="custom_configs_types_enum",
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("bw_instances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credential_ciphertext", sa.LargeBinary(length=4294967295), nullable=True))
        batch_op.add_column(sa.Column("credential_nonce", sa.LargeBinary(length=12), nullable=True))
        batch_op.add_column(sa.Column("credential_key_id", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("credential_updated_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("tls_mode", sa.Enum("off", "pinned", name="instance_tls_mode_enum"), server_default="off", nullable=False))
        batch_op.add_column(sa.Column("tls_fingerprint", sa.String(length=64), nullable=True))

    with op.batch_alter_table("bw_jobs_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error", sa.Text(), nullable=True))

    with op.batch_alter_table("bw_metadata", schema=None) as batch_op:
        batch_op.add_column(sa.Column("certificates_changed", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("last_certificates_change", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("certificate_keyring", sa.Text().with_variant(mysql.MEDIUMTEXT(), "mariadb").with_variant(mysql.MEDIUMTEXT(), "mysql"), nullable=True)
        )
        batch_op.add_column(sa.Column("certificate_keyring_active", sa.String(length=128), nullable=True))

    with op.batch_alter_table("bw_plugins", schema=None) as batch_op:
        batch_op.add_column(sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False))
        batch_op.add_column(sa.Column("icon", sa.String(length=256), nullable=True))

    with op.batch_alter_table("bw_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("case_insensitive", sa.Boolean(), server_default=sa.text("0"), nullable=False))

    with op.batch_alter_table("bw_template_custom_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=21),
            type_=sa.Enum(
                "http",
                "stream",
                "server_http",
                "server_stream",
                "default_server_http",
                "modsec",
                "modsec_crs",
                "crs_plugins_before",
                "crs_plugins_after",
                name="custom_configs_types_enum",
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("bw_ui_users", schema=None) as batch_op:
        batch_op.alter_column(
            "method",
            existing_type=sa.Enum("api", "ui", "scheduler", "autoconf", "manual", "wizard", name="methods_enum"),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the version in bw_metadata
    op.execute("UPDATE bw_metadata SET version = '1.6.15~rc1' WHERE id = 1")
    with op.batch_alter_table("bw_ui_users", schema=None) as batch_op:
        batch_op.alter_column(
            "method",
            existing_type=sa.Enum("api", "ui", "scheduler", "autoconf", "manual", "wizard", name="methods_enum"),
            server_default=sa.text("'manual'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("bw_template_custom_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "http",
                "stream",
                "server_http",
                "server_stream",
                "default_server_http",
                "modsec",
                "modsec_crs",
                "crs_plugins_before",
                "crs_plugins_after",
                name="custom_configs_types_enum",
            ),
            type_=sa.VARCHAR(length=21),
            existing_nullable=False,
        )

    with op.batch_alter_table("bw_settings", schema=None) as batch_op:
        batch_op.drop_column("case_insensitive")

    with op.batch_alter_table("bw_plugins", schema=None) as batch_op:
        batch_op.drop_column("icon")
        batch_op.drop_column("enabled")

    with op.batch_alter_table("bw_metadata", schema=None) as batch_op:
        batch_op.drop_column("certificate_keyring_active")
        batch_op.drop_column("certificate_keyring")
        batch_op.drop_column("last_certificates_change")
        batch_op.drop_column("certificates_changed")

    with op.batch_alter_table("bw_jobs_runs", schema=None) as batch_op:
        batch_op.drop_column("error")

    with op.batch_alter_table("bw_instances", schema=None) as batch_op:
        batch_op.drop_column("tls_fingerprint")
        batch_op.drop_column("tls_mode")
        batch_op.drop_column("credential_updated_at")
        batch_op.drop_column("credential_key_id")
        batch_op.drop_column("credential_nonce")
        batch_op.drop_column("credential_ciphertext")

    with op.batch_alter_table("bw_custom_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.Enum(
                "http",
                "stream",
                "server_http",
                "server_stream",
                "default_server_http",
                "modsec",
                "modsec_crs",
                "crs_plugins_before",
                "crs_plugins_after",
                name="custom_configs_types_enum",
            ),
            type_=sa.VARCHAR(length=21),
            existing_nullable=False,
        )

    with op.batch_alter_table("bw_api_user_permissions", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_type",
            existing_type=sa.Enum(
                "instances",
                "global_config",
                "services",
                "configs",
                "plugins",
                "cache",
                "web_cache",
                "bans",
                "jobs",
                "resource_groups",
                "certificates",
                "redirects",
                "upstreams",
                "workflows",
                name="api_resource_enum",
            ),
            type_=sa.VARCHAR(length=13),
            existing_nullable=False,
        )

    op.rename_table("bw_ui_user_preferences", "bw_ui_user_columns_preferences")
    op.alter_column("bw_ui_user_columns_preferences", "key", existing_type=sa.VARCHAR(length=256), new_column_name="table_name", existing_nullable=False)
    op.alter_column("bw_ui_user_columns_preferences", "value", existing_type=sa.TEXT(), new_column_name="columns", existing_nullable=False)
    with op.batch_alter_table("bw_upstream_servers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_upstream_servers_resource_id"))

    op.drop_table("bw_upstream_servers")
    with op.batch_alter_table("bw_resource_group_usages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_resource_group_usages_plugin_id"))
        batch_op.drop_index(batch_op.f("ix_bw_resource_group_usages_group_id"))
        batch_op.drop_index(batch_op.f("ix_bw_resource_group_usages_consumer_id"))

    op.drop_table("bw_resource_group_usages")
    with op.batch_alter_table("bw_resource_group_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_resource_group_entries_group_id"))

    op.drop_table("bw_resource_group_entries")
    op.drop_table("bw_workflows")
    op.drop_table("bw_upstreams")
    with op.batch_alter_table("bw_ui_user_webauthn_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_ui_user_webauthn_credentials_user_name"))
        batch_op.drop_index(batch_op.f("ix_bw_ui_user_webauthn_credentials_credential_id"))

    op.drop_table("bw_ui_user_webauthn_credentials")
    with op.batch_alter_table("bw_resource_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_resource_groups_plugin_id"))

    op.drop_table("bw_resource_groups")
    with op.batch_alter_table("bw_resource_attachments", schema=None) as batch_op:
        batch_op.drop_index("ix_bw_resource_attachments_service_primary")
        batch_op.drop_index(batch_op.f("ix_bw_resource_attachments_resource_id"))

    op.drop_table("bw_resource_attachments")
    op.drop_table("bw_redirects")
    with op.batch_alter_table("bw_certificates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_certificates_valid_to"))
        batch_op.drop_index(batch_op.f("ix_bw_certificates_common_name"))

    op.drop_table("bw_certificates")
    op.drop_table("bw_resources")
    with op.batch_alter_table("bw_metrics_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_status"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_server_name"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_security_mode"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_request_id"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_reason"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_protocol"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_ip"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_instance_hostname"))
        batch_op.drop_index("ix_bw_metrics_requests_date_server")
        batch_op.drop_index(batch_op.f("ix_bw_metrics_requests_date"))

    op.drop_table("bw_metrics_requests")
    with op.batch_alter_table("bw_metrics_baseline", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_metrics_baseline_status"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_baseline_server_name"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_baseline_request_id"))
        batch_op.drop_index(batch_op.f("ix_bw_metrics_baseline_instance_hostname"))
        batch_op.drop_index("ix_bw_metrics_baseline_date_server")
        batch_op.drop_index(batch_op.f("ix_bw_metrics_baseline_date"))

    op.drop_table("bw_metrics_baseline")
    with op.batch_alter_table("bw_bans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bw_bans_revoked_at"))
        batch_op.drop_index(batch_op.f("ix_bw_bans_ip"))
        batch_op.drop_index("ix_bw_bans_active")

    op.drop_table("bw_bans")
    # ### end Alembic commands ###
