ssl_certificate_by_lua_block {
	local class         = require "middleclass"
	local clogger       = require "bunkerweb.logger"
	local helpers       = require "bunkerweb.helpers"
	local utils         = require "bunkerweb.utils"
	local cdatastore    = require "bunkerweb.datastore"
	local cclusterstore = require "bunkerweb.clusterstore"
	local cjson         = require "cjson"
	local ssl			= require "ngx.ssl"

	local ngx = ngx
	local ngx_req = ngx.req
	local is_internal = ngx_req.is_internal
	local ERR = ngx.ERR
	local INFO = ngx.INFO
	local clear_certs = ssl.clear_certs
	local set_cert = ssl.set_cert
	local set_priv_key = ssl.set_priv_key
	local require_plugin = helpers.require_plugin
	local new_plugin = helpers.new_plugin
	local call_plugin = helpers.call_plugin
	local tostring = tostring

	-- Start ssl_certificate phase
	local logger    = clogger:new("SSL-CERTIFICATE")
	local internalstore = cdatastore:new(ngx.shared.internalstore)
	logger:log(INFO, "ssl_certificate phase started")

	-- Get plugins order
	local order, err = internalstore:get("plugins_order", true)
	if not order then
		logger:log(ERR, "can't get plugins order from internalstore : " .. err)
		return
	end

		local function get_phase_order(ord, phase, server_name)
			if ord.per_site and server_name and ord.per_site[server_name] and ord.per_site[server_name][phase] then
				return ord.per_site[server_name][phase]
			elseif ord.global and ord.global[phase] then
				return ord.global[phase]
			end
			return ord[phase]
		end

		local server_name = ssl.server_name()
		local phase_order = get_phase_order(order, "ssl_certificate", server_name)

	-- Call ssl_certificate() methods
	logger:log(INFO, "calling ssl_certificate() methods of plugins ...")
	for i, plugin_id in ipairs(phase_order) do
		-- Require call
		local plugin_lua, err = require_plugin(plugin_id)
		if plugin_lua == false then
			logger:log(ERR, err)
		elseif plugin_lua == nil then
			logger:log(INFO, err)
		else
			-- Check if plugin has ssl_certificate method
			if plugin_lua.ssl_certificate ~= nil then
				-- New call
				local ok, plugin_obj = new_plugin(plugin_lua)
				if not ok then
					logger:log(ERR, plugin_obj)
				else
					local ok, ret = call_plugin(plugin_obj, "ssl_certificate")
					if not ok then
						logger:log(ERR, ret)
					elseif not ret.ret then
						logger:log(ERR, plugin_id .. ":ssl_certificate() call failed : " .. ret.msg)
					else
						logger:log(INFO, plugin_id .. ":ssl_certificate() call successful : " .. ret.msg)
						if ret.status then
							logger:log(INFO, plugin_id .. " is setting certificate/key : " .. ret.msg)
							local ok, err = clear_certs()
							if not ok then
								logger:log(ERR, "error while clearing certificates : " .. err)
							end
							ok, err = set_cert(ret.status[1])
							if not ok then
								logger:log(ERR, "error while setting certificate : " .. err)
							else
								local ok, err = set_priv_key(ret.status[2])
								if not ok then
									logger:log(ERR, "error while setting private key : " .. err)
								else
									logger:log(INFO, "certificate set by " .. plugin_id)
									return true
								end
							end
						end
					end
				end
			else
				logger:log(INFO, "skipped execution of " .. plugin_id .. " because method ssl_certificate() is not defined")
			end
		end
	end
	logger:log(INFO, "called ssl_certificate() methods of plugins")

	logger:log(INFO, "ssl_certificate phase ended")

	return true
}
