#!/usr/bin/env python3
"""Server-side translation: Flask-Babel, and the rule for picking a locale.

Lot A of the native-i18n work. Until now every string was translated in the browser: the page
shipped in English, i18next fetched a 2338-key JSON catalog, then rewrote the DOM. That costs a
visible flash of English on every load, a full-document scan per page, and it makes anything
rendered after that scan (a table row built on draw, a toast) responsible for re-translating
itself. Serving the page already translated removes all three.

The two runtimes coexist during the migration: a template that has been converted uses `_()` and
arrives translated, one that has not still carries `data-i18n` and is translated by i18next. Both
read the same message ids, because `misc/dev/i18n/json_to_po.py` generates the gettext catalogs
from the same JSON files i18next loads.
"""

from concurrent.futures import ThreadPoolExecutor
from contextlib import suppress
from functools import lru_cache
from hashlib import sha256
from json import dumps, loads
from logging import getLogger
from os.path import join
from pathlib import Path
from re import compile as re_compile, sub
from typing import Iterator, List, Optional, Tuple

from flask import g, has_app_context, has_request_context, request, session
from flask_babel import Babel
from flask_login import current_user
from jinja2 import pass_context
from markupsafe import Markup

import plugin_extensions  # type: ignore

from app.lang_config import DEFAULT_LANGUAGE, SUPPORTED_LANGUAGE_CODES, babel_locale, ui_language

LOGGER = getLogger("UI")

# What `request.accept_languages` is matched against, and the identifiers the catalogs are
# stored under — `pt_BR` and `zh_Hant`, not the UI's `br` and `tw`. See lang_config.
SUPPORTED_LOCALES = tuple(babel_locale(code) for code in sorted(SUPPORTED_LANGUAGE_CODES))
RTL_LANGUAGE_CODES = frozenset({"ar", "ur"})
# Sheets with a `css/rtl/` twin generated by misc/dev/build-rtl-css.sh (keep in sync with its SOURCES).
RTL_SHEETS = frozenset(
    {
        "css/core.css",
        "css/theme-default.css",
        "css/overrides.css",
        "css/pages/auth-legacy.css",
        "css/pages/cache.css",
        "css/pages/crowdsec.css",
        "css/pages/groups.css",
        "css/pages/home.css",
        "css/pages/login.css",
        "css/pages/logs.css",
        "css/pages/web-cache.css",
        "libs/datatables/datatables.min.css",
    }
)

# Where a plugin's own catalog lives, relative to the plugin's root — checked in order, first
# match wins. 12 of the 13 PRO plugins ship a Flask blueprint and put it under that blueprint's
# static folder; `alerting` has no blueprint (a plain `ui/template.html` page) and puts it directly
# under `ui/static/`. Both layouts are what `window.BunkerWebExtraI18nPath` used to point PRO's own
# i18next fetch at, so adopting this extension point moves no file either way. `en.json` is the
# mandatory fallback; other languages are optional. No `plugin.json` declaration is required —
# shipping the file is the whole opt-in, so there is no build step for a plugin author to run.
#
# `locales/` at the plugin root comes first: it is the one place a plugin WITHOUT a UI can ship
# translations for its `plugin.json` metadata (name, description, setting labels and help) and
# for the templates it owns. A plugin reads ONE of these directories, the first that has the
# requested language or `en.json`, so a plugin that ships a root `locales/` keeps its page
# strings there too.
PLUGIN_LOCALES_SUBPATHS: Tuple[Tuple[str, ...], ...] = (
    ("locales",),
    ("ui", "blueprints", "static", "locales"),
    ("ui", "static", "locales"),
)

# The sub-namespaces of a plugin's catalog that translate `plugin.json` / `template.json` metadata
# (`<id>.meta.name`, `<id>.settings.<SETTING>.help`, `<id>.templates.<tpl>.name`, ...). They are
# resolved server-side only, through `plugin_text` / `setting_text`, and never shipped to the
# browser: the whole core corpus is about 10.7k English words, which `browser_catalog` would
# otherwise add to the blocking script in front of every page.
PLUGIN_METADATA_SUBTREES = ("meta", "settings", "templates")
# The pseudo-plugin that owns `src/common/settings.json`: it has no plugin directory, so its
# `general.settings.*` strings live in the core catalogs.
GENERAL_PLUGIN_ID = "general"
# `json_to_po.INTERPOLATION`: an i18next `{{name}}` placeholder.
_PLACEHOLDER = re_compile(r"\{\{\s*(\w+)\s*\}\}")


def resolve_locale() -> str:
    """The locale for this request.

    An explicit choice beats a guess, and the most recent explicit choice wins:

    1. the session language — the last deliberate pick in *this* browser that could not be saved
       to the account: an anonymous visitor on the login page, a read-only database, an API write
       that failed. `/set_language` clears this key the moment a save succeeds, so it can never
       shadow a newer saved preference.
       On `/login` only, a `?lang=` hint comes next: the same kind of pick, carried in the URL.
    2. the signed-in user's saved language — their default, and it follows them between browsers
    3. `Accept-Language`, matched against the locales that have a catalog
    4. English

    The order matters: with the user record first, nobody on a read-only database could change
    language at all, because their unsaveable choice would lose to the record every time.

    Never raises: a request that cannot resolve a locale still has to render a page, and
    Flask-Babel calls this from places that are not always one.
    """
    if not has_request_context():
        return DEFAULT_LANGUAGE

    language = session.get("language")
    if language in SUPPORTED_LANGUAGE_CODES:
        return babel_locale(language)

    # `/logout` sends the language the user was reading as `/login?lang=` (its `Clear-Site-Data`
    # wipes any session write). The login view stores it for the next request, but this request's
    # locale is resolved before the view runs (the tab title in `before_request`), so it is read
    # here too: otherwise the page after logout rendered half English (Q6-M2).
    language = request.args.get("lang") if request.endpoint == "login.login_page" else None
    if language in SUPPORTED_LANGUAGE_CODES:
        return babel_locale(language)

    with suppress(Exception):
        if current_user and current_user.is_authenticated:
            language = getattr(current_user, "language", None)
            if language in SUPPORTED_LANGUAGE_CODES:
                return babel_locale(language)

    best = request.accept_languages.best_match(SUPPORTED_LOCALES)
    if best:
        return best

    return DEFAULT_LANGUAGE


def locale_tag() -> str:
    """The resolved locale as a BCP-47 language tag, for `<html lang>`.

    Gettext identifiers use an underscore (`pt_BR`); HTML wants a hyphen. The attribute has to
    follow the rendered language or a screen reader reads French copy with English pronunciation
    rules — and with the chrome now translated on the server, a hardcoded `lang="en"` is wrong on
    every non-English page load rather than only after the DOM pass.
    """
    return resolve_locale().replace("_", "-")


def locale_code() -> str:
    """The resolved locale as the UI's own language code — `br`, not `pt_BR`.

    The JSON catalogs the browser loads are named by these codes, and so is `/set_language`. Only
    gettext and `<html lang>` use the CLDR identifier.
    """
    return ui_language(resolve_locale())


def locale_direction() -> str:
    """The native writing direction for the resolved UI language."""
    return "rtl" if locale_code() in RTL_LANGUAGE_CODES else "ltr"


def rtl_sheet(filename: str) -> str:
    """Static path of a stylesheet: its rtlcss twin under `css/rtl/` when the UI language is right-to-left."""
    if filename in RTL_SHEETS and locale_direction() == "rtl":
        return "css/rtl/" + filename.removeprefix("css/")
    return filename


def _plugin_roots() -> Tuple[Path, ...]:
    """The on-disk plugin roots to scan for a shipped catalog — the same three the `extensions.*`
    mechanism scans (`plugin_extensions.py`), read as module attributes rather than imported by
    name so a test's `monkeypatch.setattr(plugin_extensions, ...)` is honoured here too."""
    return (
        Path(plugin_extensions.CORE_PLUGINS_PATH),
        Path(plugin_extensions.EXTERNAL_PLUGINS_PATH),
        Path(plugin_extensions.PRO_PLUGINS_PATH),
    )


def _plugin_dirs(roots: Optional[Tuple[Path, ...]] = None) -> Iterator[Tuple[int, Path]]:
    """Yield `(root_index, plugin_dir)` for every readable plugin root."""
    for root_index, root in enumerate(roots if roots is not None else _plugin_roots()):
        if not root.is_dir():
            continue
        try:
            plugin_dirs = sorted(entry for entry in root.iterdir() if entry.is_dir())
        except OSError:
            continue
        yield from ((root_index, plugin_dir) for plugin_dir in plugin_dirs)


def _plugin_catalog_paths(roots: Optional[Tuple[Path, ...]] = None) -> Iterator[Tuple[int, Path]]:
    """Yield every plugin catalog path in the layouts understood by the loader."""
    for root_index, plugin_dir in _plugin_dirs(roots):
        for subpath in PLUGIN_LOCALES_SUBPATHS:
            locales_dir = plugin_dir.joinpath(*subpath)
            try:
                for catalog_file in sorted(locales_dir.glob("*.json")):
                    if catalog_file.is_file():
                        yield root_index, catalog_file
            except OSError:
                continue


def _load_catalog_file(locales_dir: Path, lang: str, plugin_name: str) -> Optional[dict]:
    """The raw parsed catalog dict from `locales_dir/<lang>.json`, falling back to that same
    directory's `en.json`, or None if it has neither file (or only an invalid one). Returned
    whole, top-level keys uninspected: a stray key outside the plugin's own id is still the
    caller's `_merge_plugin_catalog`'s problem to warn about, not something to drop silently here.
    Invalid JSON is a WARNING naming the plugin and file, never an exception — one broken catalog
    must not break every other plugin's, or even this plugin's other layout."""
    for candidate in dict.fromkeys((lang, DEFAULT_LANGUAGE)):
        catalog_file = locales_dir / f"{candidate}.json"
        if not catalog_file.is_file():
            continue
        try:
            catalog = loads(catalog_file.read_text(encoding="utf-8"))
        except (OSError, ValueError) as e:
            LOGGER.warning(f"Plugin '{plugin_name}': invalid i18n catalog {catalog_file}: {e}")
            continue
        if isinstance(catalog, dict):
            return catalog
        LOGGER.warning(f"Plugin '{plugin_name}': i18n catalog {catalog_file} is not a JSON object")
    return None


def _plugin_catalog(plugin_dir: Path, lang: str) -> Optional[dict]:
    """The plugin's own catalog dict for `lang`, falling back to its `en.json`, or None if it
    ships neither layout (or ships this locale only, invalid).

    A plugin can ship up to two `locales/` layouts at once: the root one
    (`PLUGIN_LOCALES_SUBPATHS[0]`) for its `plugin.json` / `template.json` metadata — the only
    layout available to a plugin with no UI at all — and a `ui/…/locales/` one for the page strings
    its Flask blueprint renders. Reading only the first match (as before) silently dropped whichever
    half the other layout owned. When both are present they are merged: the root layout wins on
    `PLUGIN_METADATA_SUBTREES` under the plugin's own id (metadata is its business), the UI layout
    wins on every other top-level key there (page strings are its business), and a key only one
    side ships passes through unchanged. Every OTHER top-level key either file has (a namespace
    violation, or a dotted id) also passes through unchanged, so `_merge_plugin_catalog` downstream
    still sees — and warns about — it exactly as it would for a single-layout plugin. Each layout
    still falls back to its OWN `en.json` independently when `lang` is missing from it — the two
    layouts are not required to ship the same set of languages.

    Not process-cached: a plugin's files can change under a running process (install, upgrade,
    reload), unlike the core catalogs `_core_catalog` below memoises. `_plugin_catalogs_for_request`
    memoises this for the lifetime of one request instead, which is enough to keep a plugin
    template's `_()` calls from re-scanning the disk once per key while still re-reading on the
    very next request.
    """
    plugin_id = plugin_dir.name
    root_catalog = _load_catalog_file(plugin_dir.joinpath(*PLUGIN_LOCALES_SUBPATHS[0]), lang, plugin_id)
    ui_catalog = None
    for subpath in PLUGIN_LOCALES_SUBPATHS[1:]:
        ui_catalog = _load_catalog_file(plugin_dir.joinpath(*subpath), lang, plugin_id)
        if ui_catalog is not None:
            break

    if root_catalog is None:
        return ui_catalog
    if ui_catalog is None:
        return root_catalog

    merged = dict(ui_catalog)
    root_own = root_catalog.get(plugin_id)
    if isinstance(root_own, dict):
        ui_own = merged.get(plugin_id)
        own = dict(ui_own) if isinstance(ui_own, dict) else {}
        for key, value in root_own.items():
            if key in PLUGIN_METADATA_SUBTREES or key not in own:
                own[key] = value
        merged[plugin_id] = own
    for key, value in root_catalog.items():
        if key != plugin_id and key not in merged:
            merged[key] = value
    return merged


def iter_plugin_catalogs(lang: str, roots: Optional[Tuple[Path, ...]] = None) -> Iterator[Tuple[str, dict]]:
    """Yield `(plugin_id, catalog)` for every plugin under `roots` (default: `_plugin_roots()`)
    that ships a catalog at one of `PLUGIN_LOCALES_SUBPATHS` for `lang` or `en`. Never raises: a
    root that does not exist, or that this process cannot list, is silently skipped. `lang` is
    trusted to be a validated UI code by its one caller (`_merged_catalog`, behind `_core_catalog`'s
    allow-list check) — guarded here too, since this is a public-looking helper a future caller
    could hand request data to.
    """
    if lang not in SUPPORTED_LANGUAGE_CODES:
        lang = DEFAULT_LANGUAGE
    for _, plugin_dir in _plugin_dirs(roots):
        catalog = _plugin_catalog(plugin_dir, lang)
        if catalog is not None:
            yield plugin_dir.name, catalog


def _plugin_catalogs_for_request(lang: str) -> List[Tuple[str, dict]]:
    """`iter_plugin_catalogs(lang)`, memoised for the lifetime of one request.

    A plugin page can call `_()` dozens of times, and every one of them is a core-catalog miss by
    construction — without this, each of those misses re-scans every plugin root and re-parses
    every catalog it finds. `flask.g` is per-request, so the memo is gone before the next request
    even starts: a plugin install, upgrade or reload is visible immediately, unlike `_core_catalog`
    above (which is correct to cache for the process lifetime, because the core files cannot
    change under it). Outside a request or app context (a script, a bare test call) this falls
    back to the uncached scan every time — correct, just not memoised.
    """
    if not has_app_context():
        return list(iter_plugin_catalogs(lang))
    cache = g.setdefault("_plugin_i18n_catalogs", {})
    if lang not in cache:
        cache[lang] = list(iter_plugin_catalogs(lang))
    return cache[lang]


def _plugin_namespaces_for_request(lang: str) -> dict:
    """`{plugin_id: <the plugin's own subtree>}` for `lang` (each plugin falling back to its `en`
    file whole, as `_plugin_catalog` does), memoised per request like the scan it reads. First root
    wins on a duplicate id, the rule `_merged_catalog` applies. A subtree that is not a JSON object,
    or an id with a dot, is dropped here: `_merge_plugin_catalog` already warns about both.

    Read directly instead of walking `_merged_catalog`: that merge is not memoised, and a settings
    page asks for two strings per setting — hundreds of full merges per render otherwise."""
    cache = g.setdefault("_plugin_i18n_namespaces", {}) if has_app_context() else {}
    if lang not in cache:
        namespaces: dict = {}
        for plugin_id, catalog in _plugin_catalogs_for_request(lang):
            own = catalog.get(plugin_id)
            if "." not in plugin_id and isinstance(own, dict):
                namespaces.setdefault(plugin_id, own)
        cache[lang] = namespaces
    return cache[lang]


def _setting_nodes_for_request(lang: str) -> dict:
    """`{SETTING_ID: {"label": ..., "help": ...}}` gathered from every plugin's own `settings`
    subtree for `lang`, first plugin wins (core root first, so an external plugin cannot restate a
    core setting). Setting ids are unique across plugins, so a caller that renders a setting it did
    not get from its plugin (a template step lists settings of many plugins) needs no owner id."""
    cache = g.setdefault("_plugin_i18n_setting_nodes", {}) if has_app_context() else {}
    if lang not in cache:
        nodes: dict = {}
        for own in _plugin_namespaces_for_request(lang).values():
            settings = own.get("settings")
            if isinstance(settings, dict):
                for setting_id, node in settings.items():
                    if isinstance(node, dict):
                        nodes.setdefault(setting_id, node)
        cache[lang] = nodes
    return cache[lang]


def _request_ui_language() -> str:
    """The UI code of the locale gettext resolved for this render — `get_locale()`, like
    `gettext_or_plugin`, so a forced locale is honoured."""
    from flask_babel import get_locale

    try:
        return ui_language(str(get_locale() or DEFAULT_LANGUAGE))
    except Exception:
        return DEFAULT_LANGUAGE


def _text(value) -> Optional[str]:
    return value if isinstance(value, str) and value else None


def plugin_text(plugin_id: Optional[str], key_path: str, fallback=""):
    """Display text for `<plugin_id>.<key_path>` (`meta.name`, `templates.low.name`, a widget's
    `title_i18n`, ...), or `fallback` — the raw `plugin.json` / `template.json` / widget string.

    One string at a time, each falling back on its own: the core catalogs (they hold
    `general.settings.*`), then the plugin's catalog for the active language, then its `en.json`,
    then `fallback`. A plugin that ships a partial catalog, or none, still renders every string —
    in English. Display only: never write the result back into `plugin_data` (the compose shelf
    derives `USE_<NAME>` from the raw name)."""
    if not plugin_id or not key_path:
        return fallback
    try:
        found = _text(translated(f"{plugin_id}.{key_path}"))
        for lang in dict.fromkeys((_request_ui_language(), DEFAULT_LANGUAGE)):
            if found:
                break
            found = _text(_dotted_lookup(_plugin_namespaces_for_request(lang).get(plugin_id, {}), key_path))
    except Exception:
        LOGGER.exception(f"Plugin '{plugin_id}': could not resolve i18n key '{key_path}'")
        return fallback
    return found or fallback


def setting_text(setting_id: Optional[str], field: str, fallback=""):
    """`plugin_text` for a setting's `label` or `help`, resolved by setting id alone. A `multiple`
    setting's suffixed id (`REVERSE_PROXY_URL_1`) reads its base setting's strings."""
    if not setting_id or not field:
        return fallback
    try:
        found = _text(translated(f"{GENERAL_PLUGIN_ID}.settings.{setting_id}.{field}"))
        base_id = sub(r"_\d+$", "", setting_id)
        for lang in dict.fromkeys((_request_ui_language(), DEFAULT_LANGUAGE)):
            if found:
                break
            nodes = _setting_nodes_for_request(lang)
            node = nodes.get(setting_id) or nodes.get(base_id) or {}
            found = _text(node.get(field))
    except Exception:
        LOGGER.exception(f"Setting '{setting_id}': could not resolve its i18n {field}")
        return fallback
    return found or fallback


def plugin_catalog_fingerprint() -> str:
    """Return a short fingerprint of installed plugin catalog files.

    # ponytail: size + mtime_ns can miss same-size rewrites in one coarse mtime tick; hash content
    # if deployments need stronger invalidation than this cheap per-file stat sweep.
    """
    if has_app_context() and "_plugin_i18n_catalog_fingerprint" in g:
        return g._plugin_i18n_catalog_fingerprint

    roots = _plugin_roots()
    entries = []
    for root_index, catalog_file in _plugin_catalog_paths(roots):
        try:
            stat = catalog_file.stat()
        except OSError:
            continue
        root = roots[root_index]
        entries.append((f"{root_index}:{catalog_file.relative_to(root)}", stat.st_size, stat.st_mtime_ns))
    if not entries:
        fingerprint = "0"
    else:
        digest = sha256(repr(sorted(entries)).encode("utf-8")).hexdigest()
        fingerprint = digest[:12]

    if has_app_context():
        g._plugin_i18n_catalog_fingerprint = fingerprint
    return fingerprint


# Suppresses a repeat WARNING for a collision this process has already logged once. Without it,
# every `_()` miss re-runs the whole merge (`_merged_catalog` isn't cached, only the disk scan
# is — see `_plugin_catalogs_for_request`), so a single page render with N missed keys against a
# plugin that collides on M paths logs N x M lines: measured at 1350 WARNING lines for one real
# page (30 misses x the 45 genuine collisions the stock PRO catalogs produce). The set is
# process-lifetime, matching `_core_catalog`'s cache — a collision fixed by editing a plugin's
# catalog goes quiet again only on the next worker restart, which is an acceptable trade for not
# drowning every other WARNING in the log on every request.
_WARNED_COLLISIONS: set = set()


def _merge_plugin_catalog(base: dict, overlay: dict, plugin_id: str) -> dict:
    """`overlay` merged onto `base`, returned as a NEW dict — `base` is never mutated, because it
    may be `_core_catalog`'s cached, shared dict, or another plugin's already-merged result.

    SEC-W20 F-04: an overlay may only contribute leaves under its OWN top-level id (`plugin_id.*`
    — the plugin's directory name, the same string `iter_plugin_catalogs` yields it as). Every
    other top-level key in `overlay` is refused wholesale, with ONE aggregate WARNING naming the
    overlay plugin and the offending key prefixes — never per leaf, so a catalog with N bad keys
    logs one line, not N. This is what stops a plugin directory named `aaa_evil` from claiming
    `user_manager.page.title`: the top-level key `user_manager` isn't `aaa_evil`'s own id, so it
    is refused before any leaf-level comparison runs — regardless of load order relative to the
    real `user_manager` plugin. Before this guard, whichever plugin's catalog merged first won the
    leaf, and the collision WARNING named the plugin that merged *second* (the victim), not the
    shadower.

    An earlier, broader rule let a plugin add a NEW leaf under a namespace core (or another
    plugin) already owns — e.g. `button.new_action` from a plugin that isn't `button` — because 2
    of the 13 real PRO catalogs (`user_manager`, `easy_resolve`) nest 179 of their own strings
    under core top-level names (`button`, `flash`, `footer`, ...) for unrelated keys. That
    broader rule is also what let `aaa_evil` claim `user_manager.*`, so it does not survive this
    fix: those two plugins now need their own top-level namespace too (see docs/plugins.md
    "Plugin translations") — security over convenience.

    Every top-level key that isn't `plugin_id` is refused wholesale, once per distinct offending
    set (Criticos round 1 R2): without dedup, an unmemoised miss (`_merged_catalog` isn't cached,
    only the plugin disk scan is) re-runs this on every `_()` miss, so one page render against a
    violating plugin would log once per miss rather than once — the exact flood
    `_WARNED_COLLISIONS` already exists to prevent on the leaf path below.

    `overlay[plugin_id]` and any value already at `base[plugin_id]` are both required to be a JSON
    object before any merge happens (Criticos round 1 R1): a plugin catalog is untrusted, attacker-
    controlled input past this point (any plugin install), and treating a non-dict there as a dict
    would crash `_merge_plugin_leaf`'s `.items()` on every request — turning a malformed file into
    a UI-wide denial of service — or silently discard a real core string.

    Within the allowed `plugin_id.*` subtree, a leaf that already has a concrete value (set by
    core, or by an earlier plugin sharing this exact plugin_id across two roots — see
    `iter_plugin_catalogs`, first-root-wins is accepted there since `bw_plugins.id` is a primary
    key and both install paths derive the directory name from it) is still refused leaf-by-leaf,
    with its own WARNING — unchanged from before.

    A `plugin_id` containing a dot (`PLUGIN_NAME_RX` in `src/ui/app/utils.py` allows one) gets a
    catalog no lookup can ever reach: both `_dotted_lookup` below and the browser's `t()` split a
    key on `.`, so only `{plugin_id: {...}}` is accepted by the guard above, and nothing under it
    is reachable through the dotted path the dot itself implies (Criticos round 2 C1). Silently
    merging it in would still cost the disk-scan and merge work for a catalog whose every string
    forever renders as its own raw key — a plugin author's mistake stays invisible without this
    WARNING, once per plugin like every other refusal here.
    """
    if "." in plugin_id:
        marker = (plugin_id, "dotted-id")
        if marker not in _WARNED_COLLISIONS:
            _WARNED_COLLISIONS.add(marker)
            LOGGER.warning(f"Plugin '{plugin_id}' i18n catalog is unreachable: its own id contains '.', so no dotted lookup key can ever resolve into it")
        return base

    offending = sorted(key for key in overlay if key != plugin_id)
    if offending:
        marker = (plugin_id, "namespace", tuple(offending))
        if marker not in _WARNED_COLLISIONS:
            _WARNED_COLLISIONS.add(marker)
            LOGGER.warning(f"Plugin '{plugin_id}' i18n catalog claims key(s) outside its own namespace ('{plugin_id}.*'); refusing: {', '.join(offending)}")

    if plugin_id not in overlay:
        return base

    own = overlay[plugin_id]
    if not isinstance(own, dict):
        marker = (plugin_id, "own-not-an-object")
        if marker not in _WARNED_COLLISIONS:
            _WARNED_COLLISIONS.add(marker)
            LOGGER.warning(f"Plugin '{plugin_id}' i18n catalog's own key '{plugin_id}' is not a JSON object; ignoring")
        return base

    existing = base.get(plugin_id, {})
    if not isinstance(existing, dict):
        marker = (plugin_id, "existing-not-an-object")
        if marker not in _WARNED_COLLISIONS:
            _WARNED_COLLISIONS.add(marker)
            LOGGER.warning(f"Plugin '{plugin_id}' i18n key '{plugin_id}' collides with an existing non-namespace value; keeping the existing one")
        return base

    merged = base.copy()
    merged[plugin_id] = _merge_plugin_leaf(existing, own, plugin_id, plugin_id)
    return merged


def _merge_plugin_leaf(base, overlay: dict, plugin_id: str, path: str) -> dict:
    """Leaf-level merge within a plugin's own `plugin_id.*` subtree — a leaf collides, not a whole
    namespace: the merge descends into a key both sides define as a dict, and only refuses (with a
    WARNING naming the dotted path and the plugin) at the point where `base` already has a
    concrete value."""
    merged = base.copy() if isinstance(base, dict) else {}
    for key, value in overlay.items():
        full_path = f"{path}.{key}"
        if key not in merged:
            merged[key] = value
            continue
        existing = merged[key]
        if isinstance(value, dict) and isinstance(existing, dict):
            merged[key] = _merge_plugin_leaf(existing, value, plugin_id, full_path)
        else:
            collision = (plugin_id, full_path)
            if collision not in _WARNED_COLLISIONS:
                _WARNED_COLLISIONS.add(collision)
                LOGGER.warning(f"Plugin '{plugin_id}' i18n key '{full_path}' collides with an existing key; keeping the existing one")
    return merged


@lru_cache(maxsize=len(SUPPORTED_LANGUAGE_CODES))
def _core_catalog(static_folder: str, lang: str) -> Optional[dict]:
    """The parsed core JSON catalog for `lang`, or None. Cached: the core catalogs are baked into
    the image and cannot change under a running process — unlike a plugin's (see `_plugin_catalog`),
    which is why only the core half of `_merged_catalog` is memoised for the process lifetime.

    The eighteen catalogs are at strict key parity, enforced by `test_i18n_catalogs`, so there is
    no English fallback to apply here: a locale either has every core key or the suite is already
    red. A plugin catalog is different — merged in unparsed, with its own `en` fallback.
    """
    if lang not in SUPPORTED_LANGUAGE_CODES:
        return None
    path = join(static_folder, "locales", f"{lang}.json")
    if not Path(path).is_file():
        return None
    with open(path, "r", encoding="utf-8") as messages:
        return loads(messages.read())


def _merged_catalog(static_folder: str, lang: str) -> Optional[dict]:
    """The core catalog with every loaded plugin's own catalog merged in (own-namespace-only,
    leaf-level within it, core wins — see `_merge_plugin_catalog`), or None if there is no core
    catalog for `lang`. The one structure `browser_catalog` serialises as-is and `gettext_or_plugin`
    walks one dotted key at a time, so a key resolves (or doesn't) exactly the same way in both
    places. Two different plugins can no longer collide with each other (each only ever writes its
    own top-level id): the only surviving inter-plugin collision is two catalogs sharing the exact
    same plugin_id across two roots, which resolves first-root-wins the same way a plugin-vs-core
    collision does.
    """
    core = _core_catalog(static_folder, lang)
    if core is None:
        return None
    merged = core  # do not mutate: this may still be `_core_catalog`'s cached dict, by reference
    for plugin_id, catalog in _plugin_catalogs_for_request(lang):
        merged = _merge_plugin_catalog(merged, catalog, plugin_id)
    return merged


def _dotted_lookup(catalog: dict, key: str) -> Optional[str]:
    """`catalog["a"]["b"]` for dotted `key` `"a.b"`, or None if any segment is missing or the
    leaf isn't a string (partial path, or a whole namespace rather than one message)."""
    node = catalog
    for part in key.split("."):
        if not isinstance(node, dict) or part not in node:
            return None
        node = node[part]
    return node if isinstance(node, str) else None


def browser_catalog(static_folder: str, lang: str) -> Optional[str]:
    """The JavaScript the browser loads for `lang`, or None if there is no core catalog.

    This payload is a standalone JS response (`/locales/<lang>.js`), served as its own file and
    never inlined into an HTML `<script>` body — never change that without re-adding HTML escaping
    for `</script>` (SEC-W20 F-08).

    The JSON is emitted verbatim and still nested, because `t()` walks the dots: flattening it
    here would repeat every key's prefix on the wire for no gain. Served this way — a plain
    script rather than the XHR i18next used to make — the catalog is a parse-time constant, which
    is what let the readiness flag and the whole DOM-rewriting pass go away.

    `_merged_catalog` does the actual merge (core + every loaded plugin's own catalog for `lang`,
    falling back to its `en`). Only the active language is ever emitted — the script stays sync
    and small regardless of how many plugins are installed.
    """
    merged = _merged_catalog(static_folder, lang)
    if merged is None:
        return None

    # The metadata subtrees (`PLUGIN_METADATA_SUBTREES`) stay server-side: filtered out of a copy,
    # one namespace at a time, so `_merged_catalog` — and the core dict it may share — is untouched.
    # Only a namespace a plugin catalog contributed, plus `general`, is filtered: core's own
    # `logs.meta` or `navigation.templates` are page strings the browser needs.
    stripped = None
    for namespace in (GENERAL_PLUGIN_ID, *_plugin_namespaces_for_request(lang)):
        own = merged.get(namespace)
        if isinstance(own, dict) and any(isinstance(own.get(subtree), dict) for subtree in PLUGIN_METADATA_SUBTREES):
            stripped = stripped or merged.copy()
            stripped[namespace] = {key: value for key, value in own.items() if key not in PLUGIN_METADATA_SUBTREES or not isinstance(value, dict)}
    merged = stripped or merged

    # Re-serialised without the source file's indentation: this is a blocking script in front
    # of every page script, and the pretty-printing is a third of its weight (140 KB -> 90 KB
    # for French).
    #
    # U+2028/U+2029 are valid JSON but not valid inside a JS statement on engines predating
    # ES2019 (SEC-W20 F-08): either one raw in a string literal terminates the statement early,
    # turning the rest of a catalog value into a syntax error at parse time. `ensure_ascii=False`
    # is what lets them through unescaped in the first place — everything else `dumps` emits is
    # already JS-safe.
    body = dumps(merged, separators=(",", ":"), ensure_ascii=False).replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    return f'window.BW_I18N={body};window.BW_LANG="{lang}";'


def init_i18n(app) -> Babel:
    """Attach Flask-Babel. `translations/` sits next to `main.py`, inside what every image copies
    with `COPY src/ui ui`, so no packaging target can ship without the catalogs."""
    app.config.setdefault("BABEL_DEFAULT_LOCALE", DEFAULT_LANGUAGE)
    app.config.setdefault("BABEL_DEFAULT_TIMEZONE", "UTC")
    app.context_processor(lambda: {"ui_locale_tag": locale_tag(), "ui_locale_code": locale_code(), "ui_locale_direction": locale_direction()})
    # Globals, not context: the plugin page renders through its own `Environment` seeded from
    # `jinja_env.globals` (routes/plugins.py), which a context processor never reaches.
    app.jinja_env.globals.update(plugin_text=plugin_text, setting_text=setting_text, rtl_sheet=rtl_sheet)
    babel = Babel(app, locale_selector=resolve_locale)

    # `json_to_po.py` compiles the core JSON catalogs into `translations/*/LC_MESSAGES/messages.mo`
    # at build time — a plugin's catalog cannot join that .mo without a build step, which the
    # extension point promises no plugin author has to run. So instead of touching the converter,
    # the gettext callable Flask-Babel just installed into Jinja is re-installed with a plugin
    # fallback: unchanged on a `.mo` hit, and on a miss (an untranslated lookup echoes its own key
    # — see `translated()` below) it walks `_merged_catalog` — the exact same core+plugins
    # structure `browser_catalog` serialises — for the same dotted id a plugin's template would
    # already call `_()` with.
    #
    # This needs no separate "is that already a core key" check, even though the `.mo` and the
    # core JSON do NOT have identical key sets: `json_to_po.py` folds each plural pair into one
    # `.mo` entry (`msgid`/`msgid_plural`), so the plural half (e.g.
    # `modal.body.delete_confirmation_alert_plural`) exists in the JSON but is never a standalone
    # `.mo` id — a real, if harmless, divergence, not the parity the JSON-vs-JSON locale check
    # enforces. What actually makes the check unnecessary is `_merge_plugin_catalog`: it already
    # refuses a plugin value at any leaf the core JSON defines, with a WARNING, *before*
    # `_merged_catalog` is built — so a `.mo` miss that happens to be a real core JSON leaf (one of
    # the folded plural ids) still resolves to the core string here, never a plugin's.
    #
    # `get_locale()` — not `locale_code()` — on purpose: it is the locale `get_translations()` just
    # resolved the core catalog against, so a test (or a caller) forcing the locale a different way
    # (`flask_babel.force_locale`) still gets a plugin fallback in the same language as the core one.
    #
    # `ngettext`/`pgettext`/`npgettext` are re-installed unchanged (flask-babel==4.0.0's own
    # `get_translations().u*gettext` lambdas, pinned in `src/ui/requirements.txt`) because
    # `install_gettext_callables` is the only way to change `gettext` without also handing it the
    # other three: their already-newstyle-wrapped versions aren't retrievable from `jinja_env.globals`
    # to pass back through unchanged, and re-wrapping an already-wrapped callable breaks it.
    from flask_babel import get_locale, get_translations

    def gettext_or_plugin(string: str) -> str:
        value = get_translations().ugettext(string)
        if value != string:
            return value
        lang = ui_language(str(get_locale() or DEFAULT_LANGUAGE))
        merged = _merged_catalog(app.static_folder or "", lang)
        if merged is None:
            return value
        found = _dotted_lookup(merged, string)
        # The JSON is not `%`-format ready: convert it exactly as `json_to_po.convert` does for
        # the `.mo` (a formatted entry: `%` doubled first, then `{{name}}` -> `%(name)s`).
        return _PLACEHOLDER.sub(r"%(\1)s", found.replace("%", "%%")) if found else value

    app.jinja_env.install_gettext_callables(
        gettext=gettext_or_plugin,
        ngettext=lambda s, p, n: get_translations().ungettext(s, p, n),
        newstyle=True,
        pgettext=lambda c, s: get_translations().upgettext(c, s),
        npgettext=lambda c, s, p, n: get_translations().unpgettext(c, s, p, n),
    )

    # Jinja's newstyle `gettext` (`jinja2.ext._make_new_gettext`) always applies `% variables`,
    # so a placeholder the caller does not pass is a KeyError that fails the whole page. The
    # docs told plugin authors `_()` cannot interpolate, so their templates call it bare on
    # strings holding `{{name}}`: keep such a placeholder visible, as it rendered before the
    # fallback above started converting it. Same wrapper otherwise; `_` resolves `gettext`.
    @pass_context
    def newstyle_gettext(__context, __string: str, **variables):
        rv = __context.call(gettext_or_plugin, __string)
        if __context.eval_ctx.autoescape:
            rv = Markup(rv)
        return rv % _KeepMissing(variables)

    app.jinja_env.globals["gettext"] = newstyle_gettext
    return babel


class _KeepMissing(dict):
    """A `%`-format mapping that renders an absent `%(name)s` as the original `{{name}}`."""

    def __missing__(self, key: str) -> str:
        return f"{{{{{key}}}}}"


def translated(key: str, /, **variables) -> Optional[str]:
    """`gettext`, but returning None when a key has no translation instead of echoing the key.

    The message ids are dotted keys (`button.create_service`), so an un-translated lookup renders
    as that key in the page — worse than useless in a UI. Callers that have a sensible fallback
    use this; templates use `_()` directly, because a key missing from the catalog is a bug the
    parity test already fails on.

    Flask-Babel is registered by `init_babel()` on the real app; a minimal test harness (a bare
    `Flask(__name__)` built to exercise one route in isolation, no `create_app()`) has no such
    extension. That is "no translation available" too, not a crash: `flash()` and route callers
    all use this as `translated(key) or "<english>"`, so degrading to `None` here falls through to
    the same English literal the caller already carries, instead of a 500 on every route this
    wave wired through `translated()`.
    """
    from flask_babel import gettext

    with suppress(RuntimeError, KeyError):
        rendered = gettext(key, **variables) if variables else gettext(key)
        return None if rendered == key else rendered
    return None


class LocaleThreadPoolExecutor(ThreadPoolExecutor):
    """A `ThreadPoolExecutor` whose tasks translate in the language of the request that queued them.

    A save task runs after its request has returned, where `translated()` has no app context and
    falls back to English: every flash a background save wrote was English in every locale (QA-UI-6
    Q6-H1). `submit` captures the app and the request's resolved locale, and the task runs inside a
    fresh app context with that locale forced. Only the app context is carried over, never the
    request: the request object is finished (and may be recycled) by the time the task runs.

    A pool opened from inside such a task (`instances_action` fans out one flash per instance) has
    no request either, only the task's app context with the forced locale: that counts too.
    """

    def submit(self, fn, /, *args, **kwargs):
        if not (has_request_context() or has_app_context()):
            return super().submit(fn, *args, **kwargs)

        from flask import current_app
        from flask_babel import force_locale, get_locale

        app = current_app._get_current_object()
        locale = None
        with suppress(Exception):  # no Babel on a bare test app: run untranslated, as before
            locale = str(get_locale() or DEFAULT_LANGUAGE)

        def run():
            with app.app_context():
                if locale is None:
                    return fn(*args, **kwargs)
                with force_locale(locale):
                    return fn(*args, **kwargs)

        return super().submit(run)


def resolve_page_title(path: str) -> Tuple[str, Optional[str]]:
    """``(current_endpoint, page_title)`` for the tab title and ``body[data-page-title]`` (L13).

    ``current_endpoint`` is the URL's *last* path segment (menu active-state, the `pro`-overlap
    check, and the column-preferences key all key off it being exactly that). For a detail page
    (`/templates/<id>`) that is the id, not a title -- so `page_title` is derived separately, from
    the *first* path segment instead, which is stable across a blueprint's list and detail pages
    alike and matches the existing `navigation.*` catalog key. `totp` has no `navigation.*` entry
    (not a sidebar item) but falls through to `totp.title`.
    """
    current_endpoint = path.split("/")[-1]
    page_title_endpoint = next((part for part in path.split("/") if part), "").replace("-", "_")
    page_title = (
        (translated(f"navigation.{page_title_endpoint}") or translated(f"breadcrumb.{page_title_endpoint}") or translated(f"{page_title_endpoint}.title"))
        if page_title_endpoint
        else None
    )
    return current_endpoint, page_title
