SUPPORTED_LANGUAGES = [
    {"code": "en", "name": "English", "flag": "us.svg", "english_name": "English"},
    {"code": "zh", "name": "简体中文", "flag": "cn.svg", "english_name": "Simplified Chinese"},
    {"code": "hi", "name": "हिन्दी", "flag": "in.svg", "english_name": "Hindi"},
    {"code": "es", "name": "Español", "flag": "es.svg", "english_name": "Spanish"},
    {"code": "ar", "name": "العربية", "flag": "ae.svg", "english_name": "Arabic"},
    {"code": "fr", "name": "Français", "flag": "fr.svg", "english_name": "French"},
    {"code": "bn", "name": "বাংলা", "flag": "bd.svg", "english_name": "Bengali"},
    {"code": "pt", "name": "Português", "flag": "pt.svg", "english_name": "Portuguese"},
    {"code": "br", "name": "Português (Brasil)", "flag": "br.svg", "english_name": "Brazilian Portuguese"},
    {"code": "ru", "name": "Русский", "flag": "ru.svg", "english_name": "Russian"},
    {"code": "ur", "name": "اردو", "flag": "pk.svg", "english_name": "Urdu"},
    {"code": "de", "name": "Deutsch", "flag": "de.svg", "english_name": "German"},
    {"code": "ko", "name": "한국어", "flag": "kr.svg", "english_name": "Korean"},
    {"code": "tw", "name": "繁體中文", "flag": "tw.svg", "english_name": "Traditional Chinese"},
    {"code": "tr", "name": "Türkçe", "flag": "tr.svg", "english_name": "Turkish"},
    {"code": "it", "name": "Italiano", "flag": "it.svg", "english_name": "Italian"},
    {"code": "pl", "name": "Polski", "flag": "pl.svg", "english_name": "Polish"},
]
