apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bunkerweb
  labels:
  {{- include "bunkerweb.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list