apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunkerweb-scheduler
  labels:
  {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: bunkerweb-scheduler
    {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: bunkerweb-scheduler
      {{- include "bunkerweb.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.registry.imageCredentials }}
      imagePullSecrets:
        - name: regcred
    {{- else }}
      imagePullSecrets:
        - name: {{ .Values.registry.imagePullSecretName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.scheduler.podSecurityContext | nindent 8 }}
      containers:
      - name: bunkerweb-scheduler
        env:
        {{- if .Values.scheduler.env }}
        {{- range $key, $val := .Values.scheduler.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- end }}
          - name: KUBERNETES_CLUSTER_DOMAIN
            value: {{ quote .Values.kubernetesClusterDomain }}
        {{- with .Values.scheduler.envFrom }}
        envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: {{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.scheduler.image.imagePullPolicy }}
        name: bunkerweb-scheduler
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 12 }}
        {{- with .Values.scheduler.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        securityContext: 
          {{- toYaml .Values.scheduler.containerSecurityContext | nindent 12 }}
      serviceAccountName: bunkerweb
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}