apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunkerweb-controller
  labels:
  {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: bunkerweb-controller
    {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: bunkerweb-controller
      {{- include "bunkerweb.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.registry.imageCredentials }}
      imagePullSecrets:
        - name: regcred
    {{- else }}
      imagePullSecrets:
        - name: {{ .Values.registry.imagePullSecretName }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      {{- with .Values.controller.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}        
      {{- end }}
      containers:
      - name: bunkerweb-controller
        env:
        {{- if .Values.controller.env }}
        {{- range $key, $val := .Values.controller.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- end }}
          - name: KUBERNETES_CLUSTER_DOMAIN
            value: {{ quote .Values.kubernetesClusterDomain }}
        {{- with .Values.controller.envFrom }}
        envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controller.image.imagePullPolicy  }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 12 }}
        {{- with .Values.controller.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        securityContext: 
          {{- toYaml .Values.controller.containerSecurityContext | nindent 12 }}
      serviceAccountName: bunkerweb
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      