apiVersion: v1
kind: ServiceAccount
metadata:
  name: bunkerweb
  labels:
  {{- include "bunkerweb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.saBunkerweb.serviceAccount.annotations | nindent 4 }}