services:
  mymagento:
    image: bitnami/magento-archived:2
    networks:
      bw-services:
        aliases:
          - mymagento
    volumes:
      - magento-data:/bitnami/magento
    environment:
      - MAGENTO_USERNAME=admin # replace with admin username
      - MAGENTO_PASSWORD=changeme42 # replace with a stronger password
      - MAGENTO_EMAIL=contact@example.com # replace with admin email
      - MAGENTO_HOST=www.example.com # replace with your domain
      - MAGENTO_ENABLE_HTTPS=yes
      - MAGENTO_ENABLE_ADMIN_HTTPS=yes
      - MAGENTO_DATABASE_HOST=mydb
      - MAGENTO_DATABASE_NAME=magentodb
      - MAGENTO_DATABASE_USER=user
      - MAGENTO_DATABASE_PASSWORD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
      - ELASTICSEARCH_HOST=myelasticsearch
    labels:
      - bunkerweb.SERVER_NAME=www.example.com
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=http://mymagento:8080
      - |
        bunkerweb.CUSTOM_CONF_SERVER_HTTP_magento=
        proxy_busy_buffers_size 512k;
        proxy_buffers 4 512k;
        proxy_buffer_size 256k;

  myelasticsearch:
    image: bitnami/elasticsearch:7
    networks:
      bw-services:
        aliases:
          - myelasticsearch
    # ⚠️ you need to create the directory and fix permissions ⚠️
    # see setup-autoconf.sh
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data

  mydb:
    image: mariadb:11
    networks:
      bw-services:
        aliases:
          - mydb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db-root-pwd # replace with a stronger password
      - MYSQL_DATABASE=magentodb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=db-user-pwd # replace with a stronger password (must match MAGENTO_DATABASE_PASSWORD)

volumes:
  magento-data:
  elasticsearch-data:
  db-data:

networks:
  bw-services:
    external: true
    name: bw-services
