"""Docker upgrade verification of the easy-install script.

Port of dev ``0d3532e69`` (row 55 of fold-in 9). Four defects, all reachable on 1.7 before this:

* **.env was read first-wins, Compose reads it last-wins.** A file that declares a key twice --
  which is exactly what an operator produces by appending an override -- was carried over and
  re-loaded with the *first* value, so an upgrade silently re-rendered the stack against a value
  Compose never used. ``_docker_env_last_assignments`` now collapses the file the way Compose
  does, and refuses syntax it cannot round-trip instead of changing its effective value.
* **"every service reports running" was not evidence of an upgrade.** A scheduler crash-looping on
  a failed ``alembic upgrade head`` is *running* between restarts, and the old poll could sample it
  there. The wait now pins the image identity, the restart counter and the healthcheck, and
  requires the same set to stay healthy for ten seconds.
* **a hard-coded or digest-pinned image made the tag rewrite a no-op.** ``BW_TAG`` only reaches an
  image reference that interpolates it; a ``@sha256:`` pin or a hand-edited tag left the old
  version running while the installer reported an upgrade. Both are refused now, before anything
  is recreated.
* **the tag strip cut at the wrong colon.** ``localhost:5000/bunkerity/bunkerweb`` (a registry port,
  no tag) stripped to ``localhost``, so a stack on a private registry or a pull-through mirror fell
  out of the guard entirely. The strip now only fires when the *last path segment* carries a tag.

These run the extracted shell functions directly with stubbed ``docker`` / ``_docker_compose``: no
daemon, no host mutation, no ``sudo``.
"""

import os
import re
import subprocess
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[3] / "misc" / "install-bunkerweb.sh"


def _extract(*names):
    """Return the shell source of the named top-level functions, verbatim."""
    text = SCRIPT.read_text(encoding="utf-8")
    out = []
    for name in names:
        match = re.search(rf"^{re.escape(name)}\(\) \{{\n.*?^\}}\n", text, re.M | re.S)
        assert match, f"{name}() not found in {SCRIPT.name}"
        out.append(match.group(0))
    return "\n".join(out)


def _declarations():
    """The associative arrays live at top level, not in a function; without them `set -u` turns
    `_DOCKER_EXPECTED_IMAGES[bunkerweb]=` into an arithmetic subscript on an unbound variable."""
    text = SCRIPT.read_text(encoding="utf-8")
    match = re.search(r"^declare -A _DOCKER_EXPECTED_IMAGES.*$", text, re.M)
    assert match, "the verification arrays are no longer declared at top level"
    return match.group(0)


def _run(script):
    return subprocess.run(["bash", "-c", script], capture_output=True, text=True, env=os.environ | {"NO_COLOR": "1"})


# --------------------------------------------------------------------------- .env, last-wins


def test_the_env_view_is_the_one_compose_uses(tmp_path):
    """Compose keeps the last declaration of a key; so must every rewrite of the file."""
    env_file = tmp_path / ".env"
    env_file.write_text(
        "# generated by install-bunkerweb.sh\n"
        "\n"
        "HTTP_PORT=8080\n"
        "export  BW_TAG = 1.6.5\n"
        "HTTP_PORT=9090\n"
        "USE_BACKUP=no # operator note\n"
        "EMPTY=\n",
        encoding="utf-8",
    )
    out = _run(f'{_extract("_docker_env_last_assignments")}\n_docker_env_last_assignments "{env_file}"')

    assert out.returncode == 0, out.stderr
    assert out.stdout.splitlines() == ["BW_TAG=1.6.5", "HTTP_PORT=9090", "USE_BACKUP=no", "EMPTY="]


@pytest.mark.parametrize(
    "line",
    (
        'ADMIN_PASSWORD="quoted"',  # Compose strips the quotes; a verbatim rewrite would not
        "DATABASE_URI=mysql://u:p@h/${DB}",  # interpolation: the rewritten value would differ
        "TOKEN=back\\slash",  # Compose unescapes; we would not
        "NOTE=it's",  # same, for the single quote
        "this is not an assignment",  # multi-line value, YAML leftover, ...
    ),
)
def test_syntax_that_cannot_be_rewritten_is_refused(tmp_path, line):
    """Fail closed and name the line, rather than silently changing what the value means."""
    env_file = tmp_path / ".env"
    env_file.write_text(f"HTTP_PORT=8080\n{line}\n", encoding="utf-8")

    out = _run(f'{_extract("_docker_env_last_assignments")}\n_docker_env_last_assignments "{env_file}"')

    assert out.returncode == 1
    assert "Unsupported Docker .env syntax at line 2" in out.stderr
    assert out.stdout == "", "a refused file must not emit a half-parsed view"


def test_a_carried_over_key_keeps_its_effective_value(tmp_path):
    """The custom keys an upgrade re-appends must carry the value the stack was actually running."""
    old = tmp_path / "old.env"
    old.write_text("USE_BACKUP=yes\nUSE_BACKUP=no\n", encoding="utf-8")
    new = tmp_path / ".env"
    new.write_text("BW_TAG=1.7.0\n", encoding="utf-8")

    out = _run(f"""
        set -u
        print_status() {{ :; }}
        _bw_shred() {{ rm -f "$1"; }}
        DOCKER_ENV_FILE="{new}"
        _DOCKER_ENV_SNAPSHOT="{old}"
        {_extract("_docker_env_last_assignments", "_docker_restore_env_extras")}
        _docker_restore_env_extras
        """)

    assert out.returncode == 0, out.stderr
    assert new.read_text(encoding="utf-8").splitlines() == ["BW_TAG=1.7.0", "USE_BACKUP=no"]


def test_the_preload_reads_the_last_declaration(tmp_path):
    """_docker_load_existing_env pins ports and the project name; first-wins moved a live stack."""
    env_file = tmp_path / ".env"
    env_file.write_text("HTTP_PORT=8080\nBW_TAG=1.6.5\nHTTP_PORT=9090\nBW_TAG=1.6.15\n", encoding="utf-8")

    out = _run(f"""
        set -u
        print_warning() {{ :; }}
        INSTALL_TYPE="full"; MANAGER_IP_INPUT=""
        DOCKER_ENV_FILE="{env_file}"; _DOCKER_ENV_LOADED="no"
        DOCKER_DB_PASSWORD_GENERATED=""; DOCKER_TOTP_KEY_GENERATED=""
        DOCKER_FLASK_SECRET_GENERATED=""; DOCKER_API_TOKEN_GENERATED=""
        UI_ADMIN_USERNAME_INPUT=""; UI_ADMIN_PASSWORD_INPUT=""
        API_USERNAME_INPUT=""; API_PASSWORD_INPUT=""; DOCKER_DATABASE_URI=""
        DOCKER_HTTP_PORT=""; DOCKER_HTTPS_PORT=""; DOCKER_UI_PORT=""
        DOCKER_API_PORT=""; DOCKER_FASTAPI_PORT=""; DOCKER_API_URL=""
        BUNKERWEB_INSTANCES_INPUT=""; DOCKER_LOADED_WHITELIST=""
        DOCKER_PROJECT_NAME=""; DOCKER_INSTALLED_TAG=""; _BW_RECORDED_COMPOSE_SHA256=""
        {_extract("_docker_env_last_assignments", "_docker_load_existing_env")}
        _docker_load_existing_env
        echo "HTTP=$DOCKER_HTTP_PORT TAG=$DOCKER_INSTALLED_TAG"
        """)

    assert out.returncode == 0, out.stderr
    assert "HTTP=9090 TAG=1.6.15" in out.stdout


# ------------------------------------------------------- image identity, before anything is recreated

_STUBS = """
        set -u
        print_error() {{ echo "ERROR: $*"; }}
        print_warning() {{ echo "WARN: $*"; }}
        print_status() {{ :; }}
        UPGRADE_SCENARIO="yes"
        DOCKER_IMAGE_TAG="1.7.0-beta"
        {declarations}
        _docker_compose() {{
            case "$1 $2" in
                "config --services") printf '%s\\n' {services} ;;
                "ps -a") echo "cid-$4" ;;
                "config "*) printf 'services:\\n  %s:\\n    image: %s\\n' "$2" "{image}" ;;
            esac
        }}
        docker() {{
            case "$1 $2" in
                "image inspect") echo "sha256:$(printf '%s' "$5" | tr -c 'a-z0-9' '-')" ;;
                "inspect --format") echo 0 ;;
            esac
        }}
        {functions}
"""


def _verification_script(image, services="bunkerweb"):
    return _STUBS.format(
        image=image,
        services=services,
        declarations=_declarations(),
        functions=_extract("_docker_service_image", "_docker_prepare_upgrade_verification"),
    )


def test_a_digest_pinned_image_is_refused():
    """BW_TAG cannot reach a @sha256: reference, so the rewrite would report an upgrade that never happened."""
    out = _run(_verification_script("bunkerity/bunkerweb@sha256:" + "a" * 64) + "\n_docker_prepare_upgrade_verification")

    assert out.returncode == 1
    assert "pinned by digest" in out.stdout


@pytest.mark.parametrize(
    ("image", "expected"),
    (
        # Stripping at the FIRST colon left the repository as "localhost", which matches nothing.
        ("localhost:5000/bunkerity/bunkerweb:1.7.0-beta", "health=yes"),
        # Negative control: the guard really is the repository match, not the service name.
        ("localhost:5000/someone/else:1.7.0-beta", "health=no"),
    ),
)
def test_a_registry_port_survives_the_tag_strip(image, expected):
    """A private registry or a pull-through mirror must stay inside the guard.

    The service is deliberately NOT one of the names the second `case` covers, so the answer can
    only come from the repository match. These two rows pin that the match happens at all; they
    cannot tell a conditional strip from an unconditional one, because on a TAGGED reference both
    produce the same repository -- that is what the untagged test below is for.
    """
    out = _run(_verification_script(image, services="bw-edge") + """
        _docker_prepare_upgrade_verification
        echo "health=${_DOCKER_HEALTH_REQUIRED[bw-edge]:-no}"
        """)

    assert out.returncode == 0, out.stdout + out.stderr
    assert expected in out.stdout


def test_an_untagged_registry_port_reference_stays_inside_the_guard():
    """The reference the strip's `case "${_repo##*/}" in *:*)` wrapper actually exists for.

    Strip the last colon-suffix unconditionally and `localhost:5000/bunkerity/bunkerweb` becomes
    `localhost`, which matches nothing -- the guard silently stops applying to every stack on a
    private registry or a pull-through mirror. Untagged means `:latest`, so once the repository IS
    recognised the tag comparison refuses it, which is both the correct answer and only reachable
    because the strip cut the right colon.
    """
    out = _run(_verification_script("localhost:5000/bunkerity/bunkerweb", services="bw-edge") + "\n_docker_prepare_upgrade_verification")

    assert out.returncode == 1, out.stdout + out.stderr
    assert "does not match the requested BunkerWeb image" in out.stdout


def test_a_hand_edited_tag_is_refused():
    """The stub resolves each reference to its own id, so a pinned old tag never matches the requested one."""
    out = _run(_verification_script("bunkerity/bunkerweb:1.6.5") + "\n_docker_prepare_upgrade_verification")

    assert out.returncode == 1
    assert "does not match the requested BunkerWeb image" in out.stdout


def test_a_matching_tag_is_accepted():
    """Control: the same path with the requested tag resolves and records a baseline."""
    out = _run(_verification_script("bunkerity/bunkerweb:1.7.0-beta") + """
        _docker_prepare_upgrade_verification
        echo "baseline=${_DOCKER_RESTART_COUNTS[cid-bunkerweb]:-unset}"
        """)

    assert out.returncode == 0, out.stdout + out.stderr
    assert "baseline=0" in out.stdout


def test_infrastructure_is_watched_but_not_required_to_be_healthy():
    """mariadb / redis ship no HEALTHCHECK; requiring one would time out every install."""
    out = _run(_verification_script("mariadb:11", services="bw-db") + """
        _docker_prepare_upgrade_verification
        echo "health=${_DOCKER_HEALTH_REQUIRED[bw-db]:-no} watched=${_DOCKER_EXPECTED_IMAGES[bw-db]+yes}"
        """)

    assert out.returncode == 0, out.stdout + out.stderr
    assert "health=no watched=yes" in out.stdout


# --------------------------------------------------------------------------- the readiness verdict

_WAIT_STUBS = """
        set -u
        print_status() {{ echo "STATUS: $*"; }}
        print_warning() {{ echo "WARN: $*"; }}
        DOCKER_WAIT_TIMEOUT={timeout}
{clock}
        declare -A _DOCKER_EXPECTED_IMAGES=([bunkerweb]="sha256:expected")
        declare -A _DOCKER_RESTART_COUNTS=([cid-bunkerweb]="0")
        declare -A _DOCKER_HEALTH_REQUIRED=([bunkerweb]="yes")
        _docker_compose() {{ echo "cid-bunkerweb"; }}
        docker() {{ echo "{state}"; }}
        {functions}
        wait_for_docker_stack_ready
        echo "rc=$?"
"""


# A virtual clock, so a test of the stability window costs no wall time. `_delay` is always an
# integer (`$((deadline - _now))`, clamped to 2), so `sleep` never sees a float.
_VIRTUAL_CLOCK = """        _CLOCK=1000
        date() { echo "$_CLOCK"; }
        sleep() { _CLOCK=$((_CLOCK + $1)); }"""


def _wait_script(state, timeout=1, clock=""):
    return _WAIT_STUBS.format(state=state, timeout=timeout, clock=clock, functions=_extract("wait_for_docker_stack_ready"))


def test_a_container_that_restarted_during_deployment_is_a_hard_failure():
    """The crash-looping scheduler this replaced _docker_verify_scheduler_migration for."""
    out = _run(_wait_script("sha256:expected 3 running healthy"))

    assert "rc=1" in out.stdout
    assert "restarted during deployment" in out.stdout


def test_an_unexpected_image_is_a_hard_failure():
    """Something recreated the container from an image this run did not resolve."""
    out = _run(_wait_script("sha256:someone-elses 0 running healthy"))

    assert "rc=1" in out.stdout
    assert "unexpected image" in out.stdout


def test_the_success_verdict_needs_ten_seconds_of_healthy_samples():
    """The verdict the whole deployment is gated on, and the only one with a time component.

    What is pinned here is the ten-second **duration**: one healthy sample never returns 0, and the
    deadline must not expire first. `date` and `sleep` are replaced by a virtual clock, so those ten
    seconds cost no wall time and `elapsed` is exact.

    Deliberately NOT pinned: the other half of the same condition, `[ "$_sample" != "$_previous" ]`,
    which restarts the window when the container **set** changes. These fixtures cannot reach it —
    the `_docker_compose` stub returns the same single cid on every iteration — so dropping that
    clause leaves this test green. Covering it needs a stub that changes its answer mid-wait, which
    is a second test and not this port's job.
    """
    out = _run(_wait_script("sha256:expected 0 running healthy", timeout=60, clock=_VIRTUAL_CLOCK) + '\necho "elapsed=$((_CLOCK - 1000))"')

    assert "rc=0" in out.stdout
    assert "remained healthy for 10 seconds" in out.stdout
    assert "elapsed=10" in out.stdout, out.stdout


def test_a_slow_start_is_not_reported_as_a_failed_upgrade():
    """Verdict 2: the deadline expired with no evidence either way. The stack stays up."""
    out = _run(_wait_script("sha256:expected 0 running starting"))

    assert "rc=2" in out.stdout
    assert "left running and nothing was rolled back" in out.stdout


# --------------------------------------------------------------------------- operator-owned files


def test_a_symlinked_compose_is_never_rewritten(tmp_path):
    """The renderers use `cat >`, which follows the link and truncates a file outside the stack."""
    target = tmp_path / "shared-compose.yml"
    target.write_text("services: {}\n", encoding="utf-8")
    link = tmp_path / "docker-compose.yml"
    link.symlink_to(target)

    out = _run(f"""
        set -u
        print_error() {{ echo "ERROR: $*"; }}
        print_status() {{ :; }}
        DOCKER_COMPOSE_FILE="{link}"
        _bw_register_secret_tmpfile() {{ :; }}
        _docker_render_compose_variant() {{ echo "REGENERATED" > "$DOCKER_COMPOSE_FILE"; }}
        _docker_compose() {{ return 0; }}
        {_extract("render_docker_compose")}
        render_docker_compose
        echo "rc=$?"
        """)

    assert "rc=1" in out.stdout
    assert "Refusing to replace a symlinked docker-compose.yml" in out.stdout
    assert target.read_text(encoding="utf-8") == "services: {}\n", "the link target must be untouched"


def test_the_originals_come_back_when_nothing_was_recreated(tmp_path):
    """Both files are rewritten before `up -d`; a failure before it must leave the stack as it was."""
    env_file = tmp_path / ".env"
    env_file.write_text("BW_TAG=1.6.15\n", encoding="utf-8")
    compose = tmp_path / "docker-compose.yml"
    compose.write_text("services: {original: true}\n", encoding="utf-8")

    out = _run(f"""
        set -u
        print_status() {{ :; }}
        print_error() {{ echo "ERROR: $*"; }}
        _bw_shred() {{ rm -f "$1"; }}
        UPGRADE_SCENARIO="yes"
        DOCKER_ENV_FILE="{env_file}"
        DOCKER_COMPOSE_FILE="{compose}"
        _DOCKER_UPGRADE_SNAPSHOT=""
        _DOCKER_RECREATION_STARTED="no"
        {_extract("_docker_snapshot_upgrade_files", "_docker_restore_upgrade_files")}
        _docker_snapshot_upgrade_files
        printf 'BW_TAG=1.7.0\\n' > "$DOCKER_ENV_FILE"
        printf 'services: {{regenerated: true}}\\n' > "$DOCKER_COMPOSE_FILE"
        _docker_restore_upgrade_files
        echo "rc=$? leftover=${{_DOCKER_UPGRADE_SNAPSHOT:-none}}"
        """)

    assert out.returncode == 0, out.stderr
    assert "rc=0 leftover=" in out.stdout
    assert env_file.read_text(encoding="utf-8") == "BW_TAG=1.6.15\n"
    assert compose.read_text(encoding="utf-8") == "services: {original: true}\n"


def test_nothing_is_restored_once_a_container_has_been_recreated(tmp_path):
    """Past `up -d` the schema may already be migrated; putting the old files back would lie about it."""
    env_file = tmp_path / ".env"
    env_file.write_text("BW_TAG=1.6.15\n", encoding="utf-8")
    compose = tmp_path / "docker-compose.yml"
    compose.write_text("services: {original: true}\n", encoding="utf-8")

    out = _run(f"""
        set -u
        print_status() {{ :; }}
        print_error() {{ echo "ERROR: $*"; }}
        _bw_shred() {{ rm -f "$1"; }}
        UPGRADE_SCENARIO="yes"
        DOCKER_ENV_FILE="{env_file}"
        DOCKER_COMPOSE_FILE="{compose}"
        _DOCKER_UPGRADE_SNAPSHOT=""
        _DOCKER_RECREATION_STARTED="no"
        {_extract("_docker_snapshot_upgrade_files", "_docker_restore_upgrade_files")}
        _docker_snapshot_upgrade_files
        printf 'BW_TAG=1.7.0\\n' > "$DOCKER_ENV_FILE"
        _DOCKER_RECREATION_STARTED=yes
        _docker_restore_upgrade_files
        echo "rc=$?"
        """)

    assert "rc=0" in out.stdout
    assert env_file.read_text(encoding="utf-8") == "BW_TAG=1.7.0\n", "the new file must survive"


# ------------------------------------------------- every operator-supplied .env value is guarded


def _env_value_guard():
    """The `for _v in ...` loop of ask_docker_preferences, verbatim.

    Extracted rather than reproduced: the defect this covers was a variable *missing from the
    list*, so a test that restates the list would have been blind to it by construction.
    """
    text = SCRIPT.read_text(encoding="utf-8")
    match = re.search(r"^    local _v\n    for _v in .*?^    done\n", text, re.M | re.S)
    assert match, "the .env value guard loop is no longer where this test extracts it from"
    return match.group(0)


@pytest.mark.parametrize(
    "variable",
    (
        "UI_ADMIN_PASSWORD_INPUT",
        "DOCKER_DB_PASSWORD_GENERATED",
        "DOCKER_API_TOKEN_GENERATED",
        "DOCKER_DATABASE_URI",
        "API_USERNAME_INPUT",
        "API_PASSWORD_INPUT",
        "BUNKERWEB_INSTANCES_INPUT",
        "MANAGER_IP_INPUT",
        # 1.7 only: dev's .env has no API_URL key, so --api-url skipped the guard here and the
        # value reached the file. Since the upgrade re-read is now fail-closed, that turned a
        # mangled value into a stack this script can no longer upgrade at all.
        "DOCKER_API_URL",
    ),
)
def test_every_operator_supplied_env_value_is_refused_when_it_cannot_be_carried(variable):
    """`.env` is rewritten and re-read on every upgrade; a value it cannot round-trip is refused
    at the point the operator supplies it, not when the next upgrade tries to read it back."""
    empties = "\n".join(
        f'{name}=""'
        for name in (
            "UI_ADMIN_PASSWORD_INPUT",
            "DOCKER_DB_PASSWORD_GENERATED",
            "DOCKER_API_TOKEN_GENERATED",
            "DOCKER_DATABASE_URI",
            "API_USERNAME_INPUT",
            "API_PASSWORD_INPUT",
            "BUNKERWEB_INSTANCES_INPUT",
            "MANAGER_IP_INPUT",
            "DOCKER_API_URL",
        )
    )
    out = _run(f"""
        set -u
        print_error() {{ echo "ERROR: $*"; }}
        {empties}
        {variable}='http://user:p$w@api.internal:8888'
        {_extract("validate_docker_env_value")}
        guard() {{
        {_env_value_guard()}
        }}
        guard
        echo "NOT REFUSED"
        """)

    assert out.returncode == 1, out.stdout
    assert "NOT REFUSED" not in out.stdout
    assert "cannot carry safely" in out.stdout
