"""Docker in-place upgrade path of the easy-install script.

The port globals (``DOCKER_HTTP_PORT`` & co.) start EMPTY so an upgrade can tell
"the operator passed --http-port" from "the default kicked in". Everything that
reads them therefore has to run ``_docker_default_ports`` first, and everything
that regenerates ``.env`` has to reuse what the previous ``.env`` recorded --
otherwise an upgrade silently moves a live stack back onto the default ports.
"""

import os
import re
import subprocess
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parents[3] / "misc" / "install-bunkerweb.sh"


def _extract(*names):
    """Return the shell source of the named top-level functions, verbatim."""
    text = SCRIPT.read_text(encoding="utf-8")
    out = []
    for name in names:
        match = re.search(rf"^{re.escape(name)}\(\) \{{\n.*?^\}}\n", text, re.M | re.S)
        assert match, f"{name}() not found in {SCRIPT.name}"
        out.append(match.group(0))
    return "\n".join(out)


@pytest.mark.parametrize(
    ("flag", "expected"),
    [
        ("--full", ["80 (HTTP)", "443 (HTTPS/QUIC)"]),
        ("--manager", ["7000 (Web UI)"]),
        ("--worker", ["80 (HTTP)", "443 (HTTPS/QUIC)", "5000 (API)"]),
        ("--ui-only", ["7000 (Web UI)"]),
        ("--api-only", ["8888 (FastAPI)"]),
    ],
)
def test_docker_dry_run_reports_the_host_ports(flag, expected):
    """The dry-run summary runs before ask_docker_preferences, so it has to fill
    the port defaults itself; without that it printed "Host ports:  (HTTP)"."""
    result = subprocess.run(
        ["bash", str(SCRIPT), "--docker", "--dry-run", "--yes", "--no-tui", flag],
        check=True,
        capture_output=True,
        text=True,
        env=os.environ | {"NO_COLOR": "1"},
    )
    ports_line = next(line for line in result.stdout.splitlines() if line.startswith("Host ports:"))
    for fragment in expected:
        assert fragment in ports_line, ports_line


def test_existing_env_ports_and_api_url_are_reused(tmp_path):
    """An upgrade re-renders .env from scratch; the values a running stack
    depends on must be read back out of the old file first."""
    env_file = tmp_path / ".env"
    env_file.write_text(
        "# BunkerWeb Docker stack (ui) — generated by install-bunkerweb.sh\n"
        "COMPOSE_PROJECT_NAME=custom-name\n"
        "HTTP_PORT=8080\n"
        "UI_PORT=17000\n"
        "API_URL=http://10.0.0.5:8888\n",
        encoding="utf-8",
    )
    script = f"""
        set -u
        print_warning() {{ :; }}
        INSTALL_TYPE="ui"; MANAGER_IP_INPUT=""
        DOCKER_ENV_FILE="{env_file}"; _DOCKER_ENV_LOADED="no"
        DOCKER_DB_PASSWORD_GENERATED=""; DOCKER_TOTP_KEY_GENERATED=""
        DOCKER_FLASK_SECRET_GENERATED=""; DOCKER_API_TOKEN_GENERATED=""
        UI_ADMIN_USERNAME_INPUT=""; UI_ADMIN_PASSWORD_INPUT=""
        API_USERNAME_INPUT=""; API_PASSWORD_INPUT=""; DOCKER_DATABASE_URI=""
        DOCKER_HTTP_PORT=""; DOCKER_HTTPS_PORT=""; DOCKER_UI_PORT=""
        DOCKER_API_PORT=""; DOCKER_FASTAPI_PORT=""; DOCKER_API_URL=""
        BUNKERWEB_INSTANCES_INPUT=""; DOCKER_LOADED_WHITELIST=""
        DOCKER_PROJECT_NAME=""; DOCKER_INSTALLED_TAG=""; _BW_RECORDED_COMPOSE_SHA256=""

        {_extract("_docker_load_existing_env", "_docker_default_ports")}

        _docker_load_existing_env
        _docker_default_ports
        echo "HTTP=$DOCKER_HTTP_PORT UI=$DOCKER_UI_PORT API_URL=$DOCKER_API_URL"
        echo "HTTPS=$DOCKER_HTTPS_PORT FASTAPI=$DOCKER_FASTAPI_PORT NAME=$DOCKER_PROJECT_NAME"
    """
    out = subprocess.run(["bash", "-c", script], check=True, capture_output=True, text=True).stdout

    # Recorded in .env -> reused verbatim, never reset to the standalone default.
    assert "HTTP=8080 UI=17000 API_URL=http://10.0.0.5:8888" in out
    assert "NAME=custom-name" in out
    # Absent from .env -> the standalone-deploy defaults fill in.
    assert "HTTPS=443 FASTAPI=8888" in out
