FROM fedora:36

ENV container docker

RUN dnf -y update \
    && dnf -y install systemd \
    && dnf clean all

RUN cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

# Nginx
RUN dnf update -y && \
    dnf install -y nginx-1.20.2

RUN curl -s https://packagecloud.io/install/repositories/bunkerity/bunkerweb/script.rpm.sh \
    | sed 's/yum install -y pygpgme --disablerepo='\''bunkerity_bunkerweb'\''/yum install -y python-gnupg/g' \
    | sed 's/pypgpme_check=`rpm -qa | grep -qw pygpgme`/python-gnupg_check=`rpm -qa | grep -qw python-gnupg`/g' \
    | sudo bash && \
    sudo dnf makecache && \
    sudo dnf install -y bunkerweb-1.4.5

VOLUME ["/sys/fs/cgroup"]

CMD ["/usr/sbin/init"]