key "bunkerweb-certbot." {
    algorithm hmac-sha256;
    secret "QrmNE3WJEYEMVtupVSWlznHxxTyIdR2I4LRiVPGWwpM=";
};

options {
    directory "/var/lib/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    allow-query { any; };
    recursion no;
    dnssec-validation no;
    pid-file none;
};

logging {
    channel stdout {
        stderr;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
    };
    category update { stdout; };
    category update-security { stdout; };
    category queries { stdout; };
    category default { stdout; };
};

zone "bwtest.lan" {
    type master;
    file "/var/lib/bind/bwtest.lan.zone";
    allow-update { key "bunkerweb-certbot."; };
};
