services:
  bunkerweb-all-in-one:
    image: bunkerity/bunkerweb-all-in-one:1.6.5
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    volumes:
      - bw-storage:/data
    environment:
      DATABASE_URI: "postgresql://bunkerweb:changeme@bw-db:5432/db" # Remember to set a stronger password for the database
      API_WHITELIST_IP: "127.0.0.0/8"
      SERVER_NAME: "www.example.com"
      SERVICE_UI: "no"
    networks:
      - bw-services
      - bw-db

  bw-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "bunkerweb"
      POSTGRES_PASSWORD: "changeme" # Remember to set a stronger password for the database
      POSTGRES_DB: "db"
    volumes:
      - bw-data:/var/lib/postgresql/data
    networks:
      - bw-db

volumes:
  bw-data:
  bw-storage:

networks:
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
