services:
  bunkerweb-all-in-one:
    image: bunkerity/bunkerweb-all-in-one:1.6.5
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    volumes:
      - bw-storage:/data
    environment:
      API_WHITELIST_IP: "127.0.0.0/8"
      SERVER_NAME: "www.example.com"
      SERVICE_UI: "no"
    networks:
      - bw-services

volumes:
  bw-storage:

networks:
  bw-services:
    name: bw-services
