services:
  bunkerweb-all-in-one:
    image: bunkerity/bunkerweb-all-in-one:1.6.5
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    volumes:
      - bw-storage:/data
    environment:
      DATABASE_URI: "mysql+pymysql://bunkerweb:changeme@bw-db:3306/db" # Remember to set a stronger password for the database
      API_WHITELIST_IP: "127.0.0.0/8"
      SERVER_NAME: "www.example.com"
      MULTISITE: "yes"
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      www.example.com_USE_TEMPLATE: "ui"
      www.example.com_USE_REVERSE_PROXY: "yes"
      www.example.com_REVERSE_PROXY_URL: "/changeme"
      www.example.com_REVERSE_PROXY_HOST: "http://127.0.0.1:7000"

      # UI
      ADMIN_USERNAME: "changeme"
      ADMIN_PASSWORD: "changeme"
    networks:
      - bw-services
      - bw-db

  bw-db:
    image: mysql:9
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "changeme" # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-db

volumes:
  bw-data:
  bw-storage:

networks:
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
