FROM fedora:43@sha256:a651ddf48ea28a06ed4e1e6519f51c9f47e7a5a138722ade87369b8fbb7e5b42

ENV container=docker
ENV NGINX_VERSION=1.30.4

RUN dnf -y update \
    && dnf -y install systemd \
    && dnf clean all

RUN cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

# Nginx
RUN dnf update -y && \
    dnf install -y php-fpm curl gnupg2 ca-certificates python3-pip which && \
    dnf config-manager setopt updates-testing.enabled=1 && \
    dnf install nginx-${NGINX_VERSION} -y

VOLUME ["/sys/fs/cgroup"]

CMD ["/usr/sbin/init"]
