FROM redhat/ubi8-init:8.10-5@sha256:4ac4efdcf27380828863af1221f11c7b8ea8169c3cbe2f601324b1c8b37d2e5b

ENV NGINX_VERSION 1.26.1

# Copy rocky repo
COPY src/linux/rocky-8.repo /etc/yum.repos.d/rocky.repo
RUN sed -i "s/%ARCH%/$(uname -m)/g" /etc/yum.repos.d/rocky.repo

# Copy RPM-GPG-KEY-Rocky-8
COPY src/linux/RPM-GPG-KEY-Rocky-8 /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-8

# Import RPM-GPG-KEY-Rocky-8
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-8

COPY src/linux/nginx.repo /etc/yum.repos.d/nginx.repo

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf install php-fpm curl yum-utils -y && \
    dnf install nginx-${NGINX_VERSION} -y

COPY ./package-rhel/*.rpm /opt
