FROM redhat/ubi8-init:8.10@sha256:2cf715e32e908d17546ce8eaeb31c68b2b4de1bbff82b2c16485ba6ae80d1482

ENV NGINX_VERSION=1.28.2

# Copy rocky repo
COPY src/linux/rocky-8.repo /etc/yum.repos.d/rocky.repo
RUN sed -i "s/%ARCH%/$(uname -m)/g" /etc/yum.repos.d/rocky.repo

# Copy RPM-GPG-KEY-Rocky-8
COPY src/linux/RPM-GPG-KEY-Rocky-8 /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-8

# Import RPM-GPG-KEY-Rocky-8
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-8

COPY src/linux/nginx.repo /etc/yum.repos.d/nginx.repo

RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y && \
    dnf install php-fpm yum-utils -y && \
    dnf install -y https://nginx.org/packages/rhel/8/$(uname -m)/RPMS/nginx-${NGINX_VERSION}-1.el8.ngx.$(uname -m).rpm

COPY ./package-rhel-8/*.rpm /opt
