FROM redhat/ubi9-init:9.8@sha256:1d9b8da63de5fc7bb42add5274792e7f1489f71a5d8d0f137d8d13c112d98b1d

ENV NGINX_VERSION=1.30.1

# Copy rocky repo
COPY src/linux/rocky-9.repo /etc/yum.repos.d/rocky.repo
RUN sed -i "s/%ARCH%/$(uname -m)/g" /etc/yum.repos.d/rocky.repo

# Copy RPM-GPG-KEY-Rocky-9
COPY src/linux/RPM-GPG-KEY-Rocky-9 /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9

# Import RPM-GPG-KEY-Rocky-9
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9

COPY src/linux/nginx.repo /etc/yum.repos.d/nginx.repo

RUN dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y && \
    dnf install php-fpm yum-utils -y && \
    dnf install -y https://nginx.org/packages/rhel/9/$(uname -m)/RPMS/nginx-${NGINX_VERSION}-1.el9.ngx.$(uname -m).rpm

COPY ./package-rhel-9/*.rpm /opt
