FROM quay.io/centos/centos:stream8@sha256:a8692b39e546eed9177d495db1edfd97bb6de70b9527f58aeb72f90b687c3426

RUN yum install -y initscripts  # for old "service"

ENV container=docker
ENV NGINX_VERSION 1.26.0

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

COPY src/linux/nginx.repo /etc/yum.repos.d/nginx.repo

RUN dnf install php-fpm curl yum-utils epel-release which -y && \
	dnf install nginx-${NGINX_VERSION} -y

COPY ./package-centos/*.rpm /opt

VOLUME /run /tmp

CMD /usr/sbin/init
