FROM redhat/ubi9-init:9.4-14.1726695630@sha256:4b057fecf55ad4090d95d37f2249a0a522f6603e4af60b9b75d76d415cf47d48

ENV NGINX_VERSION 1.26.2

# Copy rocky repo
COPY src/linux/rocky-9.repo /etc/yum.repos.d/rocky.repo
RUN sed -i "s/%ARCH%/$(uname -m)/g" /etc/yum.repos.d/rocky.repo

# Copy RPM-GPG-KEY-Rocky-9
COPY src/linux/RPM-GPG-KEY-Rocky-9 /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9

# Import RPM-GPG-KEY-Rocky-9
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9

COPY src/linux/nginx.repo /etc/yum.repos.d/nginx.repo

RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    dnf install php-fpm yum-utils -y && \
    dnf install nginx-${NGINX_VERSION} -y

COPY ./package-rhel9/*.rpm /opt
