#!/bin/bash

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
chmod +x manifest-tool

if [ "$SOURCE_BRANCH" = "dev" ] ; then
	./manifest-tool push from-spec multi-arch-manifest-dev.yaml
elif [ "$SOURCE_BRANCH" = "master" ] ; then
	./manifest-tool push from-spec multi-arch-manifest-master.yaml
fi
