FROM redhat/ubi8:8.7

ENV OS=rhel
ENV NGINX_VERSION 1.24.0

# Copy centos repo
COPY src/linux/centos.repo /etc/yum.repos.d/centos.repo

# Copy RPM-GPG-KEY-CentOS-Official
COPY src/linux/RPM-GPG-KEY-centosofficial /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

# Import RPM-GPG-KEY-CentOS-Official
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

# Install fpm
RUN dnf install -y ruby ruby-devel make gcc redhat-rpm-config rpm-build wget && \
  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
  rpm -Uvh epel-release*rpm && \
  dnf module -y reset ruby && dnf module -y enable ruby:2.6 && dnf module -y install ruby:2.6/common && \
  gem install fpm

# Nginx
COPY src/linux/nginx.repo /etc/yum.repos.d/nginx.repo
RUN dnf install yum-utils -y && \
  wget https://nginx.org/packages/rhel/8/x86_64/RPMS/nginx-${NGINX_VERSION}-1.el8.ngx.x86_64.rpm && \
  dnf install nginx-${NGINX_VERSION}-1.el8.ngx.x86_64.rpm -y && \
  rm -rf nginx-${NGINX_VERSION}-1.el8.ngx.x86_64.rpm

# Copy dependencies sources folder
COPY src/deps /tmp/bunkerweb/deps
COPY src/scheduler/requirements.txt /tmp/req/requirements.txt
COPY src/ui/requirements.txt /tmp/req/requirements.txt.1
COPY src/common/gen/requirements.txt /tmp/req/requirements.txt.2
COPY src/common/db/requirements.txt /tmp/req/requirements.txt.3

RUN mkdir -p /usr/share/bunkerweb/deps && \
  cat /tmp/req/requirements.txt /tmp/req/requirements.txt.1 /tmp/req/requirements.txt.2 /tmp/req/requirements.txt.3 > /usr/share/bunkerweb/deps/requirements.txt && \
  rm -rf /tmp/req

# Compile and install dependencies
RUN dnf install -y readline-devel python39-pip brotli brotli-devel gperftools-devel perl libxslt-devel libxml2 libxslt bash gd gd-devel gcc-c++ curl znc-modtcl gawk libtool pcre-devel automake autoconf gcc make openssl-devel git zlib-devel libxml2-devel pkgconf libcurl-devel geoip-devel --skip-broken && \
    pip3.9 install --no-cache-dir --upgrade pip && \
    pip3.9 install wheel && \
    #mkdir -p /usr/share/bunkerweb/deps && \
    chmod +x /tmp/bunkerweb/deps/install.sh && \
    bash /tmp/bunkerweb/deps/install.sh && \
    mkdir /usr/share/bunkerweb/deps/python && \
    pip3.9 install --no-cache-dir --require-hashes --target /usr/share/bunkerweb/deps/python -r /usr/share/bunkerweb/deps/requirements.txt

#RUN pip3.10 install --no-cache-dir --require-hashes --target /usr/share/bunkerweb/deps/python -r /tmp/bunkerweb/deps/requirements.txt

# Copy BW files
# can't exclude deps from . so we are copying everything by hand
COPY src/bw/loading /usr/share/bunkerweb/loading
COPY src/bw/lua /usr/share/bunkerweb/lua
COPY src/bw/misc /usr/share/bunkerweb/misc
COPY src/common/api /usr/share/bunkerweb/api
COPY src/common/cli /usr/share/bunkerweb/cli
COPY src/common/confs /usr/share/bunkerweb/confs
COPY src/common/core /usr/share/bunkerweb/core
COPY src/common/db /usr/share/bunkerweb/db
COPY src/common/gen /usr/share/bunkerweb/gen
COPY src/common/helpers /usr/share/bunkerweb/helpers
COPY src/common/settings.json /usr/share/bunkerweb/settings.json
COPY src/common/utils /usr/share/bunkerweb/utils
COPY src/scheduler /usr/share/bunkerweb/scheduler
COPY src/ui /usr/share/bunkerweb/ui
COPY src/VERSION /usr/share/bunkerweb/VERSION

# Setup BW
RUN cp /usr/share/bunkerweb/helpers/bwcli /usr/bin/ && \
    chmod 755 /usr/bin/bwcli && \
    mkdir -p /etc/bunkerweb/configs && \
    mkdir -p /var/cache/bunkerweb/ && \
    mkdir -p /etc/bunkerweb/plugins && \
    mkdir -p /var/tmp/bunkerweb/ && \
    mkdir -p /var/www/html && \
    mkdir -p /var/lib/bunkerweb && \
    mkdir -p /etc/letsencrypt && \
    echo "Linux" > /usr/share/bunkerweb/INTEGRATION && \
    find /usr/share/bunkerweb -path /usr/share/bunkerweb/ui/deps -prune -o -type f -exec chmod 0740 {} \; && \
    find /usr/share/bunkerweb -path /usr/share/bunkerweb/ui/deps -prune -o -type d -exec chmod 0750 {} \; && \
    chmod 770 /var/cache/bunkerweb/ /var/tmp/bunkerweb/ && \
    chmod 750 /usr/share/bunkerweb/gen/main.py /usr/share/bunkerweb/scheduler/main.py /usr/share/bunkerweb/cli/main.py /usr/share/bunkerweb/helpers/*.sh /usr/share/bunkerweb/ui/main.py /var/www/ && \
    find /usr/share/bunkerweb/core/*/jobs/* -type f -exec chmod 750 {} \; && \
    chmod 755 /usr/share/bunkerweb

# Copy Linux files
COPY src/linux/scripts /usr/share/bunkerweb/scripts
COPY src/linux/fpm.sh /usr/share/fpm.sh
RUN chmod +x /usr/share/bunkerweb/scripts/*.sh /usr/share/fpm.sh
COPY src/linux/fpm-rhel /usr/share/.fpm
COPY src/linux/bunkerweb.service /lib/systemd/system/bunkerweb.service
COPY src/linux/bunkerweb-ui.service /lib/systemd/system/bunkerweb-ui.service

# Generate RPM at startup
VOLUME /data
WORKDIR /usr/share/
ENTRYPOINT ["/usr/share/fpm.sh", "rpm"]
