ssl_certificate /var/cache/bunkerweb/misc/default-server-cert.pem;
ssl_certificate_key /var/cache/bunkerweb/misc/default-server-cert.key;
ssl_protocols {{ SSL_PROTOCOLS }};
{% if SSL_PROTOCOLS == "TLSv1.3" %}
ssl_prefer_server_ciphers off;
{% else %}
ssl_prefer_server_ciphers on;
{% endif %}
ssl_session_tickets off;
{% if "TLSv1.2" in SSL_PROTOCOLS or "TLSv1.1" in SSL_PROTOCOLS or "TLSv1" in SSL_PROTOCOLS %}
ssl_session_timeout 1d;
	{% if SSL_SESSION_CACHE_SIZE == "off" or SSL_SESSION_CACHE_SIZE == "none" %}
ssl_session_cache {{ SSL_SESSION_CACHE_SIZE }};
	{% else %}
ssl_session_cache shared:MozSSL:{{ SSL_SESSION_CACHE_SIZE }};
	{% endif %}
{% endif %}
ssl_ecdh_curve {{ resolve_ssl_ecdh_curve(SSL_ECDH_CURVE) }};
{% if "TLSv1.2" in SSL_PROTOCOLS +%}
ssl_dhparam /etc/nginx/dhparam;
	{% if SSL_CIPHERS_CUSTOM|default('')|trim != "" %}
ssl_ciphers {{ SSL_CIPHERS_CUSTOM }};
	{% else %}
		{% if SSL_CIPHERS_LEVEL == "old" %}
ssl_ciphers @SECLEVEL=0:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA;
		{% elif SSL_CIPHERS_LEVEL == "intermediate" %}
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
		{% elif SSL_PROTOCOLS != "TLSv1.3" %}
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
		{% endif %}
	{% endif %}
{% endif %}

{% set https_ports = [] %}
{% for k, port in all.items() if k.startswith("HTTPS_PORT") and port %}
	{% if https_ports.append(port) %}{% endif %}
{% endfor %}
{% if https_ports|length > 0 %}
	{% if HTTP2 == "yes" %}
http2 on;
	{% endif %}
	{% set common_options = " ssl" %}
	{% if USE_PROXY_PROTOCOL == "yes" %}
		{% set common_options = common_options ~ " proxy_protocol" %}
	{% endif %}
	{% for port in https_ports %}
listen 0.0.0.0:{{ port }}{{ common_options }};
		{% if USE_IPV6 == "yes" %}
listen [::]:{{ port }}{{ common_options }};
		{% endif %}
	{% endfor %}
{% endif %}

{% if https_ports|length > 0 and "TLSv1.3" in SSL_PROTOCOLS and HTTP3 == "yes" and USE_PROXY_PROTOCOL == "no" %}
http3 on;
	{% set http3_listen_options = " quic" %}
	{% if MULTISITE == "no" and DISABLE_DEFAULT_SERVER == "no" and IS_LOADING == "no" %}
		{% set http3_listen_options = http3_listen_options ~ " reuseport" %}
	{% endif %}
	{% for port in https_ports %}
listen 0.0.0.0:{{ port }}{{ http3_listen_options }};
		{% if USE_IPV6 == "yes" %}
listen [::]:{{ port }}{{ http3_listen_options }};
		{% endif %}
	{% endfor %}
add_header Alt-Svc 'h3=":{{ HTTP3_ALT_SVC_PORT }}"; ma=86400';
{% endif %}

{% include "partials/ssl-certificate-by-lua.conf" %}

ssl_client_hello_by_lua_block {
	-- For now, add a dummy block to avoid nginx errors when ssl_client_hello_by_lua_block is not defined in the main configuration file. This will be removed in the future when ssl_client_hello_by_lua_block will be implemented in plugins.
	return
}
