//recup depuis jinja
//multisite
//name: service ou folder
//config

const folders = {
  name: "configs",
  type: "folder",
  path: "/opt/bunkerweb/configs",
  can_create_files: False,
  can_create_folders: False,
  can_edit: False,
  can_delete: False,
  children: [
    {
      name: "default-server-http",
      type: "folder",
      path: "/opt/bunkerweb/configs/default-server-http",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
    {
      name: "default-server-stream",
      type: "folder",
      path: "/opt/bunkerweb/configs/default-server-stream",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
    {
      name: "http",
      type: "folder",
      path: "/opt/bunkerweb/configs/http",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
    {
      name: "modsec",
      type: "folder",
      path: "/opt/bunkerweb/configs/modsec",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
    {
      name: "modsec-crs",
      type: "folder",
      path: "/opt/bunkerweb/configs/modsec-crs",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
    {
      name: "server-http",
      type: "folder",
      path: "/opt/bunkerweb/configs/server-http",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [
        {
          name: "www.example.com",
          type: "folder",
          path: "/opt/bunkerweb/configs/server-http/www.example.com",
          can_create_files: True,
          can_create_folders: True,
          can_edit: True,
          can_delete: True,
          children: [
            {
              name: "hello-world.conf",
              type: "file",
              path: "/opt/bunkerweb/configs/server-http/www.example.com/hello-world.conf",
              can_edit: True,
              can_download: False,
              content:
                "CmxvY2F0aW9uIC9oZWxsbyB7CglkZWZhdWx0X3R5cGUgJ3RleHQvcGxhaW4nOwoJY29udGVudF9ieV9sdWFfYmxvY2sgewoJCW5neC5zYXkoJ3dvcmxkJykKCX0KfQo=",
            },
          ],
        },
      ],
    },
    {
      name: "server-stream",
      type: "folder",
      path: "/opt/bunkerweb/configs/server-stream",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
    {
      name: "stream",
      type: "folder",
      path: "/opt/bunkerweb/configs/stream",
      can_create_files: True,
      can_create_folders: True,
      can_edit: False,
      can_delete: False,
      children: [],
    },
  ],
};
