FROM fedora:36

ENV OS=fedora
ENV NGINX_VERSION 1.20.2

# Install fpm
RUN dnf install -y ruby ruby-devel make gcc redhat-rpm-config rpm-build && \
    gem install fpm

# Nginx
RUN dnf update -y && \
    dnf install -y curl gnupg2 ca-certificates redhat-lsb-core && \
    dnf install nginx-1.20.2 -y

# Copy dependencies sources folder
COPY bw/deps /tmp/bunkerweb/deps

# Compile and install dependencies
RUN dnf install -y python3-pip brotli brotli-devel gperftools-devel perl libxslt-devel libxml2 libxslt bash gd gd-devel gcc-c++ kernel-devel curl znc-modtcl libmpc-devel gmp-devel gawk mpfr-devel libtool pcre-devel automake autoconf readline-devel gcc make openssl-devel git zlib-devel libxml2-devel pkgconf libcurl-devel geoip-devel lmdb-devel && \
    mkdir -p /usr/share/bunkerweb/deps && \
    chmod +x /tmp/bunkerweb/deps/install.sh && \
    bash /tmp/bunkerweb/deps/install.sh && \
    mkdir /usr/share/bunkerweb/deps/python && \
    pip install --no-cache-dir --require-hashes --target /usr/share/bunkerweb/deps/python -r /tmp/bunkerweb/deps/requirements.txt

# Copy files
# can't exclude deps from . so we are copying everything by hand
COPY bw/api /usr/share/bunkerweb/api
COPY bw/core /usr/share/bunkerweb/core
COPY bw/cli /usr/share/bunkerweb/cli
COPY bw/helpers /usr/share/bunkerweb/helpers
COPY bw/lua /usr/share/bunkerweb/lua
COPY bw/misc /usr/share/bunkerweb/misc
COPY bw/gen /usr/share/bunkerweb/gen
COPY bw/settings.json etc/bunkerweb/settings.json
COPY db /usr/share/bunkerweb/db
COPY bw/confs /etc/bunkerweb/confs
COPY bw/loading /usr/share/bunkerweb/loading
COPY utils /usr/share/bunkerweb/utils
COPY VERSION /usr/share/bunkerweb/VERSION
COPY scheduler /usr/share/bunkerweb/scheduler
COPY ui /usr/share/bunkerweb/ui

# Setup BW
RUN cp /usr/share/bunkerweb/helpers/bwcli /usr/bin/ && \
    chmod 755 /usr/bin/bwcli && \
    mkdir /etc/bunkerweb/configs && \
    mkdir /var/cache/bunkerweb/ && \
    mkdir /etc/bunkerweb/plugins && \
    mkdir /var/tmp/bunkerweb/ && \
    #mkdir /var/www/html && \
    echo "Linux" > /usr/share/bunkerweb/INTEGRATION && \
    find /usr/share/bunkerweb -path /usr/share/bunkerweb/deps -prune -o -type f -exec chmod 0740 {} \; && \
    find /usr/share/bunkerweb -path /usr/share/bunkerweb/deps -prune -o -type d -exec chmod 0750 {} \; && \
    chmod 770 /var/cache/bunkerweb/ /var/tmp/bunkerweb/ && \
    chmod 750 /usr/share/bunkerweb/gen/main.py /usr/share/bunkerweb/scheduler/main.py /usr/share/bunkerweb/cli/main.py /usr/share/bunkerweb/helpers/*.sh /usr/share/bunkerweb/ui/main.py && \
    find /usr/share/bunkerweb/core/*/jobs/* -type f -exec chmod 750 {} \; && \
    pip install --no-cache-dir --target /usr/share/bunkerweb/deps/python -r /usr/share/bunkerweb/ui/deps/requirements.txt && \
	chmod 755 /usr/share/bunkerweb

# Copy Linux files
COPY linux/variables.env /etc/bunkerweb/variables.env
COPY linux/ui.env /etc/bunkerweb/ui.env
COPY linux/scripts /usr/share/bunkerweb/scripts
COPY linux/fpm.sh /usr/share/fpm.sh
RUN chmod +x /usr/share/bunkerweb/scripts/*.sh /usr/share/fpm.sh
COPY linux/fpm-ubuntu /usr/share/.fpm
COPY linux/bunkerweb.service /usr/share/bunkerweb.service
COPY linux/bunkerweb-ui.service /usr/share/bunkerweb-ui.service

# Generate DEB at startup
VOLUME /data
WORKDIR /usr/share/
ENTRYPOINT ["/usr/share/fpm.sh", "deb"]