name: Automatic test

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build -t autotest .
      - name: Run autotest
        run: docker run autotest test
      - name: Run Trivy security scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'autotest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'


