name: Plumber CI/CD security scan

on:
  schedule:
    - cron: "30 9 * * 1"
  workflow_call:

jobs:
  plumber:
    name: Analyze GitHub Actions workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write # OIDC identity required by score-push
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: .github
          persist-credentials: false
      - name: Run Plumber
        uses: getplumber/plumber@031bc86d1e5f661626e2000f4f8779912d608d5f # v0.4.39
        with:
          verify-attestation: true
          config-file: .github/plumber/plumber.yaml
          min-score: B
          soft-fail: false
          upload-sarif: true
          score-push: true
          upload-artifacts: true
