name: Plumber CI/CD security scan

on:
  push:
    branches: [master, dev, 1.7]
  pull_request:
  schedule:
    - cron: "30 9 * * 1"

permissions: read-all

jobs:
  plumber:
    name: Analyze GitHub Actions workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Plumber
        uses: getplumber/plumber@031bc86d1e5f661626e2000f4f8779912d608d5f # v0.4.39
        with:
          sparse-checkout: .github
          verify-attestation: true
          config-file: .github/plumber/plumber.yaml
          min-score: C
          soft-fail: true
          upload-sarif: true
          score-push: false
          upload-artifacts: true
