name: Pullfrog
run-name: ${{ inputs.name || github.workflow }}

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      prompt:
        type: string
        description: Agent prompt
      name:
        type: string
        description: Run name

jobs:
  pullfrog:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Run agent
        uses: pullfrog/pullfrog@7ba7c2e9daf9ed6d2e86866f1d05067e4d54bd52 # v0.1.77
        with:
          prompt: ${{ inputs.prompt }}
          progress_comments: disabled
          push: restricted
          shell: restricted
